### ISSUE TITLE
Not working for second user (cDock 3)

### ISSUE THREAD

**Issue by sapkra** [w0lfschild/cDock2#100]
Themes are not working for second user.

**Comment by defrilitus** [comment]
Actually, in my case, cDock 3 is not working at all for a second user. I installed it on the laptop I share with my wife; works fine. However, when my wife logs in and starts cDock, the app crashes with an error message as shown in the attached file. Not sure why this is, but there it is. I checked it out on my iMac as well; same result: it seems that it's impossible to have two users on the same computer. I'm perfectly willing to do any tests needed. Thanks.

![untitled](https://user-images.githubusercontent.com/34283333/38157699-4454ecbe-3457-11e8-9e4d-68e31b889bce.jpeg)

**Comment by defrilitus** [comment]
PS to my previous comment: cDock 2 worked fine with two users on the same computer. However, when I scaled back 3 to 2, I received the same error as mentioned above. Not sure what changes version 3 introduced that influence also version 2.

**Comment by sapkra** [comment]
The problem that you can't open cDock is that you don't have read and write permissions with the second user. You have to right click and set the permission and also open the app package and set read amd write permissions recursively for all files and folders.

**Comment by defrilitus** [comment]
Thank you for your quick and helpful reply. Worked perfectly 👍

**Comment by sapkra** [comment]
So you're able to set themes for the second user or can you just open cDock now?

**Comment by sapkra** [comment]
If I understand you correctly it works different for you. On my Mac the first user has the customized dock and the second one stucks on the MacOS default dock.

**Comment by defrilitus** [comment]
Correct. On my Mac, cDock works as expected for the primary user (i.e., the user who first intalled cDock3). The secondary user can open cDock and enable any personalisation options except for themes. The theme remains that of the primary user (not the macOS default dock) and cannot be changed. Works fine for us, as we are both happy to use the transparent theme.

**Comment by sapkra** [comment]
Maybe the different behavior depends on in which order we created the second user and installed cDock. In my case I installed cDock first and created the second user afterwards.

**Comment by chrisprough** [comment]
I am having the same issue. I would like to just delete out ALL files for CDock and reinstall on the main account. The first account made (where it is installed) is hardly used. 
How do I uninstall?

**Comment by defrilitus** [comment]
You should be good to go if you delete:
- cDock.app from /Applications/
- cDock.bundle from /Library/Application Support/SIMBL/Plugins/
- org.w0lf.cDock* from ~/Library/Cookies/ 
- org.w0lf.cDock* from ~/Library/Preferences/

**Comment by w0lfschild** [comment]
I finally got around to checking this out and it was a simple permissions issue.

Somehow the Paddle framework got set to no access for anything but Administrator account...

I'll have a fix out for this sometime over the weekend.

**Comment by w0lfschild** [comment]
Fix is live in version 1.1.1
