### ISSUE TITLE
Recent Applications Reflection not updating

### ISSUE THREAD

**Issue by recuerom** [w0lfschild/cDock2#101]
Regardless of what app you launch it seems that the reflection of the Recent Applications icon is not updating. The reflection you see here is from Startupizer which was the last app launched at boot.

From that point, further updates of the icon (ie app launches) are not updated on the reflection.

<img width="311" alt="screen shot 2018-04-04 at 19 02 55" src="https://user-images.githubusercontent.com/15388514/38299188-adba9620-383c-11e8-90bb-363d9633041d.png">

**Comment by w0lfschild** [comment]
Good catch, I'll check that out.

**Comment by w0lfschild** [comment]
Okay, I'll have a fix for this in the next release.

**Comment by w0lfschild** [comment]
Fix is live in 1.1.1
