### ISSUE TITLE
Dock resprings

### ISSUE THREAD

**Issue by ghost** [w0lfschild/cDock2#102]
cDock3 version 104 resprings quite often when adding stuff to the Downloads folder when downloading with a browser for instance.

It takes the whole Desktop with it which is annoying.

**Comment by ExactProbability** [comment]
[Dock_2018-04-06-084521_Allans-iMac.crash.zip](https://github.com/w0lfschild/cDock2/files/1883012/Dock_2018-04-06-084521_Allans-iMac.crash.zip)

This is the latest crash for the issue I mention. I recently made a whole new install with SIMBL and cDock as the only injectors. Not even having themed the OS by replacing .car files and cDock still crashes when anything touches the Downloads folder from Safari. The issue also goes for Google Chrome downloads.

**Comment by minimum91** [comment]
I'm getting occasional crashes on 10.13.4 but on 10.11.6 it often goes into crash loops. Have not figured out what causes this behaviour.

**Comment by ExactProbability** [comment]
I have only one crash from cDock in the Console here on El Capitan. I decided to downgrade to experience my cursors again and other stuff. cDock has been installed for a couple of days alongside the installation of El Capitan. It's more stable, for me, on El Capitan than it ever was on High Sierra. Kinda odd how stable cDock is now as opposed to High Sierra.

**Comment by w0lfschild** [comment]
I can't get this to consistently replicate but I'm thinking it has something to do with icon reflections for the downloads folder maybe.
