### ISSUE TITLE
[Feature Request] Even less blur in macOS!

### ISSUE THREAD

**Issue by minimum91** [w0lfschild/cDock2#103]
Probably might not relate to cDock at all, but my favorite feature of cDock is the ability to remove the "frosted glass" layers from everything like the Dock, dock labels, App Switcher, Mission Control etc. I would love to be able to turn it off for dropdown menus, the menu bar etc as well. Would this be possible? Thank you for doing gods work for macOS!

**Comment by ExactProbability** [comment]
Could you try this out as what is depicted in the screenshot? 
The image is of System Preferences.
<img width="668" alt="lesstransparency" src="https://user-images.githubusercontent.com/25787371/38491023-03da3fae-3beb-11e8-995e-57e95ec9128d.png">

**Comment by minimum91** [comment]
I already have this turned on, but this is not what I'm asking for here. I want the menus to be transparent, but not have the blur layer. When you turn this on - everything becomes coloured in an unpleasant gray, which I use right now. I want these menus to be slightly transparent black.

**Comment by ExactProbability** [comment]
Apologies .. I've only managed, via a macOS theme to make the menus slightly transparent black.. but with blur - I'm not sure why the blur persists but I now understand fully what you mean.

**Comment by w0lfschild** [comment]
This doesn't sound like something specific enough to the Dock to be part of cDock. Also just not likely for me to as a mySIMBL plugin either.

**Comment by minimum91** [comment]
:(
