### ISSUE TITLE
1.0.5 Updates [cDock3]?

### ISSUE THREAD

**Issue by dockdude** [w0lfschild/cDock2#106]
Version 1.0.0 to 1.0.4 was quick, but little activities since. Can we get a teaser of upcoming fixes, enhancements and maybe new features?

Thanks,

**Comment by w0lfschild** [comment]
1.1.0

*	New
	*	Hide any application from the Dock

*	Fixed
	*	Fix hot corners failing to open Mission control
	*	Hiding Finder and Trash are now separate from theming
	*	Mission control auto-show and Launchpad dots are now separate from theming
	*	Dock size shrinking to minimum when changing Dock position
	*	Font related crash
	*	Fix error when scrolling on System Integrity Protection video

**Comment by dockdude** [comment]
I'd thought Automatic Updates is not working because I am still running 1.0.4, but realized 1.1.0 is now out yet. Thanks for the teaser and looking forward to the official release. Dockdude.

**Comment by w0lfschild** [comment]
1.1.0 is out with the following changes

*	New
	*	Hide any application from the Dock
	*	Ability to add Flex spacer tiles
	*	Activate/Deactivate license button

*	Fixed
	*	Hot corners failing to open Mission control
	*	Handoff icon badge displaying text instead of icon
	*	Hiding Finder and Trash are now separate from theming
	*	Mission control auto-show and Launchpad dots are now separate from theming
	*	Trash can badge option is now separate from theming
	*	Dock size shrinking to minimum when changing Dock position
	*	Font related crash
	*	Fix error when scrolling on System Integrity Protection video
	*	Updated to latest Paddle and Dev-Mate
	*	Bug fixes
