### ISSUE TITLE
Indicator Lights NOT Showing after Dock Crash

### ISSUE THREAD

**Issue by marianco** [w0lfschild/cDock2#112]
I'm using cDock 1.0.4
on MacOS High Sierra 10.13.4 (17E202) on a MacBook Pro (MacBookPro11,3)

After cDock crashes, the indicator lights no longer appear.

They do not re-appear:
1) if I restart Dock
2) no matter what theme I subsequently change to
3) no matter what theme setting I turn on or off

Restarting the Mac allows the indicator lights to re-appear.

**Comment by rapierbit** [comment]
After using cDock for quite some time (over a year?), this same thing happened to me just in the last 2-3 days for the first time. Had to reboot to regain indicator lights. 10.12.6 on a MacPro3,1.

**Comment by rapierbit** [comment]
Update: no the reboot did NOT work to regain indicator lights. Had to delete all preferences and set dock back to defaults, which required me to repopulate the dock from scratch.

**Comment by rapierbit** [comment]
Thanks yes I realized that later. However, I was used to cDock being able to control such things (magnification, show dock, animations, etc) without resorting to the OS Settings panel, and that no longer seemed to be the case. Looking forward to the next version (I've seen some of the other reported bugs so I won't add noise). Thanks for your efforts on this application.

**Comment by w0lfschild** [comment]
I think I'll add this in as an option in the "Dock Settings" tab just so it's easier for people to fix if the issue pops up for them.
