### ISSUE TITLE
cDock not working for second account

### ISSUE THREAD

**Issue by chrisprough** [w0lfschild/cDock2#114]
I installed under an account named Administrator. Works. 
I made a second account on same computer. 
It has admin privileges. 
system integrity is off. 
CSRUTIL disabled
Will NOT change the dock to save its life.

**Comment by w0lfschild** [comment]
This is something I'm looking into. Not sure what the issue is at the moment but hope to have a fix soon.

https://github.com/w0lfschild/cDock2/issues/100
