### ISSUE TITLE
3D night made my dock pic turn black and normal over and over even after restart

### ISSUE THREAD

**Issue by SwiftDevv** [w0lfschild/cDock2#116]
Do not use 3D night, it made my MacBook air from early 2016 flip out.

It has the latest macOS and the dock screen kept turning black and normal over and over, I restarted it twice, shut it down once nothing worked.

Till I pulled out cDock 1 and set the theme to default..

**Comment by DanielDeJong2** [comment]
It's not just dock it's the whole cdock 2 rip

**Comment by w0lfschild** [comment]
Hmm do you have crash logs you could upload?

`~/Library/Logs/DiagnosticReports/Dock...crash`

**Comment by DanielDeJong2** [comment]
https://mega.nz/#!ffAhQDja
like 9 of them
