### ISSUE TITLE
New Dark Boot 6.0.1 Quits on Launch

### ISSUE THREAD

**Issue by brianfos** [w0lfschild/cDock2#117]
After downloading and trying to launch the new Dark Boot 6.0.1, I can't even open the application: it quits before launching. Please see the screen shot of the error window.
![dark boot 6 0 1 quits on launch](https://user-images.githubusercontent.com/24682824/40660830-0568c320-6307-11e8-8f91-6efb270fb9ec.jpg)

**Comment by w0lfschild** [comment]
Sorry about that. Try 6.0.2

https://github.com/w0lfschild/app_updates/blob/master/DarkBoot/DarkBoot_6.0.2.zip

https://github.com/w0lfschild/DarkBoot/issues
