### ISSUE TITLE
App indicators behavior

### ISSUE THREAD

**Issue by m424m** [w0lfschild/cDock2#119]
Strange bug in cDock 3: when my dock is on the left/right side of the screen, app indicators hide with the dock as usual (they move with the dock). However, when I place dock on the bottom of the screen, indicator dots just stay on their places until the dock hides completely, and then just disappear.

MacOS High Sierra 10.13.4

**Comment by marseny42** [comment]
Yes, of course.

Normal behavior:
![normal behavior](https://user-images.githubusercontent.com/18166063/41088813-196b62d0-6a49-11e8-937d-0cfaebba5a12.gif)

cDock behavior:
![cdock behavior](https://user-images.githubusercontent.com/18166063/41088835-286cd066-6a49-11e8-8106-759b2bd728d7.gif)

**Comment by cygvis** [comment]
same here
