### ISSUE TITLE
[Feature] Dock pinning

### ISSUE THREAD

**Issue by RubyGemer** [w0lfschild/cDock2#12]
Is it possible to take all the app to the top? like in Ubuntu? 
Also, please clean full screen mode for Retina the dock overlaps little bit of menu bar

<img width="918" alt="screen shot 2015-12-29 at 11 02 03 pm" src="https://cloud.githubusercontent.com/assets/15967311/12038741/9c101dfc-ae80-11e5-93a6-3a57c8c82ea9.png">

**Comment by liam4** [comment]
Rather how to put dock on top.

But yeah, I'm not sure. You can't do it in the current version of cDock. (I think!) Feature request? :P

**Comment by RubyGemer** [comment]
@liam4 if its not there than its a features request.

**Comment by dkfiresky** [comment]
@RubyGemer Here is the [tutorial](http://osxdaily.com/2013/12/05/place-dock-corner-of-screen-mac-os-x/) on how to move Dock to that position, but it doesn't works in OS X El Capitan.

**Comment by RubyGemer** [comment]
Thanks but I wanted for EL Captain @dkfiresky

**Comment by dkfiresky** [comment]
@RubyGemer 
> This feature is not available in OS X El Capitan, so it might not be shipped with cDock itself.

**Comment by w0lfschild** [comment]
Yeah I'd have to figure out how to move the buttons which is something I'm not sure how to do right now.

Not sure what you mean about the overlap thing. Maybe it's something you can only see on retina but I don't see anything. I'm guessing you're just seeing the [1 px space below the menubar](https://www.reddit.com/r/applehelp/comments/3n4np5/1px_space_between_menu_bar_and_application/).

**Comment by RubyGemer** [comment]
@w0lfschild yes the space its merely 1 px but I am a big fan of design and cleanliness that is why I own Apple products. Thanks for such an enthusiastic behaviour you will get it done. Soon we get this kind of icon till top and no spaces

![ubuntu_1104](https://cloud.githubusercontent.com/assets/15967311/12078163/88bb1c88-b22d-11e5-85b3-d7bda41bbd21.jpg)

**Comment by dkfiresky** [comment]
@RubyGemer 
> Soon we get this kind of icon till top and no spaces

How that could be possible? Actually I would like to see that feature too. But I don't know how to implement it in OS X 10.11....

**Comment by RubyGemer** [comment]
I think @dkfiresky I am not sure what is this dock styled in xml, css, sass. If this mainly based on styles that pretty easy to tweak with, otherwise I don't know. You might wanna ask w0lfschild, how is this dock written.

**Comment by w0lfschild** [comment]
The dock doesn't have styling. I know how to move the icon pictures but not the actual clickable area.

**Comment by dkfiresky** [comment]
@RubyGemer this dock written in objective-c, c++ or swift and has some configuration available through plist file. There are no styling options at all.

**Comment by Scellow** [comment]
Dock pinning doesn't work for me 
![image](https://user-images.githubusercontent.com/27389256/37653785-4aea5cd6-2c40-11e8-8a48-b6e7d76ef33b.png)

**Comment by Scellow** [comment]
Oh nvm i added cDock to accebility list, then restarted it and now it works fine!
