### ISSUE TITLE
cDock (1.0.4) issues

### ISSUE THREAD

**Issue by mwlimoges** [w0lfschild/cDock2#120]
Spent the $5 (worth it!) and updated cDock. However, after updating, most customization tools do not respond (i.e., everything under customize ). Even after restarting the doc. I had made a custom, beautiful dock that matched my desktop wonderfully but was left with Mac OS X's standard dock theme...

UPDATE:
I managed to get cDock to work after disabling SIP... made my dock changes... then reenabled SIP. After which, the dock maintains the positioning and spacers added from cDock but I lose all the color changes... the dock defaults back to its OS X standard color scheme. Not sure how to keep the cDock changes after reenabling SIP. Please Advise. Thank you.

**Comment by mwlimoges** [comment]
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/35971251/40842324-8a3c780a-657b-11e8-9f5a-7b4e0624d3d8.png">

**Comment by mwlimoges** [comment]
SIP enabled... Kills some of my cDock tweaks (i.e., colors) but keeps others (i.e., spacers). Hmmm...
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/35971251/40842354-9fada916-657b-11e8-9a69-6525b1171508.png">

**Comment by w0lfschild** [comment]
Interesting I'm guessing it's something to do with the SIMBL components, not sure why it's working with SIP off but not with it on though.

**Comment by mwlimoges** [comment]
I managed to get cDock to work. I uninstalled, deleted, downloaded, and reinstalled both mySIMBL and cDock. After which, cDock ran without a hitch. Great product! Keep it up the excellent work!
