### ISSUE TITLE
Handover buble in Dock

### ISSUE THREAD

**Issue by Richard-i** [w0lfschild/cDock2#122]
Hello Wolf,

Any chance to fix the buble notification for handover from iPhone/iPad?

<img width="235" alt="screen shot 2018-06-05 at 09 26 17" src="https://user-images.githubusercontent.com/20862878/40958646-b0d6cefa-68a2-11e8-8ce8-fcf1c952542d.png">

**Comment by w0lfschild** [comment]
I'll look into this. Shouldn't be too hard to fix.

It probably wont match the other badge colors though since it's using a black/gray image.

**Comment by Richard-i** [comment]
To be honest I wouldn’t mind if you would keep the default phone icon there…I know what it is, no need to put txt into bubble :)

**Comment by w0lfschild** [comment]
Fixed in 1.1.0
