### ISSUE TITLE
Colors are not exactly how I picked them

### ISSUE THREAD

**Issue by gerrit-h** [w0lfschild/cDock2#126]
**Describe the bug**
I set a border color for the dock (in my case rgb(255, 219, 139)). 
But checking the color with the 'Digital Color Meter' after it is applied shows a different color (rgb(254, 212, 121))

**To Reproduce**
1. Go to 'Customize'
2. Select RGB-values for the dock border
3. Selected values do not match newly applied values

**Expected behavior**
The RGB-values I set in the cDock colorpicker match exactly the color that is shown on the dock.

**Screenshots**
This is the color I select in the colorpicker:
<img width="708" alt="colorpicker" src="https://user-images.githubusercontent.com/13509208/41596374-6e48c97a-73ca-11e8-9921-c400a1be2969.png">

This is the resulting color used for the dock:
<img width="708" alt="border" src="https://user-images.githubusercontent.com/13509208/41596372-6e2ebb3e-73ca-11e8-816c-7f862a26559e.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5 
 - Version: cDock v1.1.2

**Comment by w0lfschild** [comment]
Thanks for the detailed report, I'll look into this.

**Comment by gerrit-h** [comment]
So i just noticed something.
In my case above i wanted to set the dock border to rgb(255, 219, 139), but the color that was actually used is rgb(254, 212, 121).

After restarting cDock.app it now shows the color that was actually used as the border color instead of the value that i initially wanted to use.
<img width="1000" alt="screen shot 2018-06-28 at 13 15 02" src="https://user-images.githubusercontent.com/13509208/42031115-63d06d88-7ad5-11e8-8d2d-656241de14d0.png">

**Comment by w0lfschild** [comment]
In the color picker if you select the ⚙️ and choose generic RGB you should get matching or very close color matching (+/-1)
