### ISSUE TITLE
Deprecate WAYAppStoreWindow?

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock2#13]
Should this still be used as there are public methods to implement/control the UI?
Currently it's used only to hide window's titlebar.

Although, NSWindow's titlebarAppearsTransparent and titleVisibility properties are available since OS X 10.10, we can show default titlebar instead of hiding it.

 - OS X 10.9
![screen shot 2015-12-30 at 11 32 45 am](https://cloud.githubusercontent.com/assets/2175645/12048873/2da65ce6-aee9-11e5-8ed4-a33d669960b1.png)

 - OS X 10.10+
![screen shot 2015-12-30 at 11 09 13 am](https://cloud.githubusercontent.com/assets/2175645/12048891/5b6c2778-aee9-11e5-9900-9e6eb963e1d6.png)

**Comment by w0lfschild** [comment]
I like the consistency and as far as I'm aware there's no issues caused by using WAYAppStoreWindow versus whatever the standard implementation is in 10.10+

I'll consider this though.

**Comment by dkfiresky** [comment]
@w0lfschild I'm interested in using native (public) APIs just because of code purity and simplicity.
