### ISSUE TITLE
cDock making finder and trash icons disappear in dock

### ISSUE THREAD

**Issue by Tasglobi** [w0lfschild/cDock2#133]
After the latest software update in OS X 10.11 cDock now makes the finder and trash icons disappear in transparent dock mode....   any fixes, please?

**Comment by w0lfschild** [comment]
Make sure you don't have them set to hidden.

**Comment by Tasglobi** [comment]
Updating cDock fixed it, thanks Wolfgang        Cheers    Peter


PETER & SUE HUBER
2266 WILMOT ROAD
LOWER WILMOT,  TASMANIA  7310

WEB:   http://www.boobookhill.com/

PHONE:  0364 921 456     MOBILE: 0467 298 347

On 16 Jul 2018, at 8:13 AM, Wolfgang Baird <notifications@github.com> wrote:

Make sure you don't have them set to hidden.
