### ISSUE TITLE
Magnification does not correspond to mouseover in "show only active apps" mode

### ISSUE THREAD

**Issue by doctopus** [w0lfschild/cDock2#136]
**Description of the bug**
When "show only active apps" is selected, the icon magnification on mouseover acts erratically.
1. If dock is positioned on either side and dock is pinned to top or bottom the app icons above or below the cursor gets magnified instead of just under it; works fine if dock is pinned to the middle.
2. If dock is positioned at bottom, the magnification only works fine if dock is pinned to the middle but the magnification effect does not happen at all if dock is pinned to left or right at the bottom.

**To Reproduce**
1. Go to Dock settings -> select "show only active apps" -> Apply changes and restart. (Now you should be having less number of icons in dock than how it were before activating this setting)
2. Click on Extra settings -> Make sure the magnification is checked, with any value (27 with icon size 7 in my case), "position on screen" select either left or right, "Dock pinning" select either top or bottom. (by the way, these options should change to left and right respectively if bottom is selected in "position on screen") 
3. Hover on the dock icons
4. The zoom effect will be not where the mouse cursor is. It is either above it if dock pinning is at top, or below it if it at bottom.

**Expected behavior**
The icons which are most closer to the cursor should have the magnification effect; magnifying the icons above which the cursor is.

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Version 1.1.2

**Comment by w0lfschild** [comment]
It actually has to do with pinning not show only active apps. Thanks for the report though.

See this issue: https://github.com/w0lfschild/cDock2/issues/124

**Comment by doctopus** [comment]
Thank you for your reply. I can imagine this could be actually an issue with pinning position when its either top or bottom. The effect gets pronounced and visible when there are few apps in the dock. Since "show only active apps" decreases the number of apps on the dock, the effect gets pronounced. Kindly address this in your next release. Thank you
