### ISSUE TITLE
cDock

### ISSUE THREAD

**Issue by ussbarry** [w0lfschild/cDock2#138]
downloaded cDock 3 ,disabled system integrity protection,and i am running macOS High Sierra version 10.13.6 and cDock doesn’t work at all.I am using the trial version to see if it does as advertised…..it doesn’t.
p.s. I have tried this in 2 different Mac’s…no luck.
					please help,
					Larry

**Comment by w0lfschild** [comment]
If you install mySIMBL does it show the the .osax file is installed? The issue when things don't work is generally that it's not installing for whatever reason.
