### ISSUE TITLE
Unable to Purchase

### ISSUE THREAD

**Issue by BrianStegner** [w0lfschild/cDock2#140]
Clicking "Purchase" results in small popup window with endless "progress bar." [v.1.1.2 on macOS High Sierra]

**Comment by w0lfschild** [comment]
Probably a [Paddle](https://paddle.com/) Issue. Are you still having this problem?

**Comment by BrianStegner** [comment]
Hi Wolf,

Thanks for your note. No, I am no longer having the problem, I am an official client now, registered without any issue at all.

Thanks again,
Brian
