### ISSUE TITLE
Mac Beta 5 - Mojave

### ISSUE THREAD

**Issue by nolando44** [w0lfschild/cDock2#143]
There are many bugs when using CDock on beta 5 of mojave, any time your put the cursor to the bottom the of screen to bring up the dock the entire screen flashes black and the dock disappears. Completely unusable. trying to open trash also crashes mac.

**Comment by mscodemonkey** [comment]
Uninstalled cDock and the customisations are still there and the dock is still crashing.  Is there a way of removing everything applied by cDock for now until this is fixed?

**Comment by w0lfschild** [comment]
Delete `/Library/Application Support/SIMBL/Plugins/cDock.bundle`

**Comment by nolando44** [comment]
I also found a fix, I went into privacy and security and removed permission for cDock in “Automate”

**Comment by w0lfschild** [comment]
Should be fixed in the latest release. 1.1.3
