### ISSUE TITLE
Crash on Mojave Beta 5/6

### ISSUE THREAD

**Issue by macrex218** [w0lfschild/cDock2#144]
I am running cdock v 3.1.0 on an iMac w/OSX 10.14 beta 5.  Upon startup, the screen flashes and, the dock doesn't show.

**Comment by hansluyendijk** [comment]
Same issue here. I switched off cdock, with a tear in my eye...

**Comment by hansluyendijk** [comment]
Hope somebody knows how it can be fixed?

**Comment by w0lfschild** [comment]
@hansluyendijk It will require an update. I already have it fixed but just need to do some testing, should have an update rolled out within the week hopefully.

**Comment by Jonzzs** [comment]
@w0lfschild why I uninstall the cDock, the dock still crashing after reboot, is there any way to restore the dock to default until the bug is solved?

**Comment by w0lfschild** [comment]
@Jonzzs 

Delete `/Library/Application Support/SIMBL/Plugins/cDock.bundle`

**Comment by Jonzzs** [comment]
@w0lfschild It works, thank you!

**Comment by w0lfschild** [comment]
Should be fixed in the latest release. 1.1.3
