### ISSUE TITLE
Force Dark Menus issues

### ISSUE THREAD

**Issue by Quantumpanda** [w0lfschild/cDock2#148]
Two issues with "Force Dark Menus" in cDock v1.1.3 on macOS 10.12.6, one significant, one minor.

The significant issue: Turning on "Force Dark Menus" turns the text white but the background becomes 100% transparent rather than almost-black. See attached image 1.

![cdock issue - force dark menus 1](https://user-images.githubusercontent.com/6102262/44007473-f8bb0384-9e63-11e8-8ac6-4f424d75616c.png)

The minor issue: The settings checkbox for "Force Dark Menus" has the wrong tooltip. See attached image 2.

![cdock issue - force dark menus 2](https://user-images.githubusercontent.com/6102262/44007474-f8eb882e-9e63-11e8-9428-3b4e358cd10c.png)

**Comment by w0lfschild** [comment]
Unfortunately not sure this is something I'll be able to fix. 

The feature has been hidden / removed from current versions of cDock as it doesn't work correctly.
