### ISSUE TITLE
cDock not starting

### ISSUE THREAD

**Issue by Arketsu** [w0lfschild/cDock2#151]
I am runing Mojave Beta8 on a mackbook pro 2018

Every time I restart the computer have to perform killall Dock to activate the theme.
performed clean install. reinstalled cdock 3 no luck problem still persist.

**Comment by w0lfschild** [comment]
Interesting. You can manually try adding the helper from `/Applications/cDock.app/Contents/Resources/cDock Helper.app` to your login items.

**Comment by Arketsu** [comment]
@w0lfschild Looks like a found a way to resolve the problem.
Step 1 . press command + R and restart
step 2 . open terminal
step 3 . type: csrutil disable
step 4 . type:csrutil enable
step 5 . type: csrutil disable
step 6 . type:csrutil enable
step 7 . type: csrutil disable
step 8 . make sure csrutil is disable and restart the computer

that should fix the problem, tested multiple times with same results.

**Comment by gabrielfsousa** [comment]
how i manually add the helper from /Applications/cDock.app/Contents/Resources/cDock Helper.app

**Comment by w0lfschild** [comment]
Hopefully this issue should be fixed in the 3.0 releases.
