### ISSUE TITLE
cDock 3 install problem

### ISSUE THREAD

**Issue by randywhitehead1** [w0lfschild/cDock2#154]
I have two macs, both running Sierra 10.12.6.  On my Macbook air I was able to upgrade to Cdock 3 with no problems and then I purchased a license.  On my iMac, when I try to upgrade I get the following error message "An error occurred while extracting the archive" and it tells me to try again later.  Subsequent tries all fail.  Not sure what to do at this point?

**Comment by w0lfschild** [comment]
You could download the latest version from here : https://cdock.macenhance.com/
