### ISSUE TITLE
cDock icons stay on bar even after closing

### ISSUE THREAD

**Issue by chrisalk54** [w0lfschild/cDock2#158]
Just updated my Mac to Mojave, prior to the update when I closed a window or app the icon would disappear from the doc, now it doesn't.  I have to right click on the icon and hit 'remove icon from dock'.  This is just a minor bug in an app that I've come to love.  Wondering if anyone has any work arounds?

**Comment by w0lfschild** [comment]
That's a new Mojave feature not related to cDock. It can be turned off.

https://9to5mac.com/2018/08/29/macos-mojave-how-to-hide-recent-apps-in-the-dock/
