### ISSUE TITLE
[Mojave] cDock starting and immediately crashing over and over again upon launch.

### ISSUE THREAD

**Issue by Nobody912** [w0lfschild/cDock2#159]
---+ Issue +---
I'm new to cDock and when I installed and launched it, the application starts, but then immediately crashes. This cycle does not stop repeating and renders the application unusable.

---+ Reproduction of Issue +---
1. Open cDock

---+ System Info +---
MacBook Pro - Early 2015
Running Mojave 10.14
cDock 1.1.3
SIP is off.
I have mySIMBL (I have cDock installed there, but it seemingly doesn't do anything)

Thanks in advance!

— Nobody912

**Comment by drowtram** [comment]
me too

**Comment by stiffyfoto** [comment]
me too
