### ISSUE TITLE
[Question] [cDock-GUI] Is it possible to rewrite the GUI in swift and optimise the code?

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock2#16]
Swift is new 'modern' language...

Because of that it looks like Javascript (and I'm more Javascript developer than Objective-C, C++, etc.)
it's easier to write on swift rather then on objective-c (at least for me).

I can make a fork of [cDock-GUI](https://github.com/w0lfschild/cDock2/tree/master/cDock/cDock-GUI) and remove (or rewrite) all the stuff like `PFMoveApplication `, `PFAboutWindow`, `WAYAppStoreWindow`, `WAYWindow`.

But I have the following question: will you then merge my changes when the time comes, or I should not even try to do this? My priority is to make all the code clean and simple.

PS: I can support new features you add to cDock in my fork as well, so there might be no problems in differences between GUI or user experience.

**Comment by w0lfschild** [comment]
Sure but not if it's losing functionality.

**Comment by dkfiresky** [comment]
Thanks for your reply. I will try to rewrite everything without loosing any feature.
