### ISSUE TITLE
How Does ActiveDock Manage a Transparent Dock on Mojave With SIP Enabled?

### ISSUE THREAD

**Issue by defrilitus** [w0lfschild/cDock2#162]
I understand the SIP issues put into place by Mojave. But how does [ActiveDock](https://www.noteifyapp.com/activedock/) manage a transparent (or coloured) dock, even with SIP enabled?

**Comment by Arketsu** [comment]
if im not wrong active dock replace's the Mac dock while cdock modifies the Mac dock

**Comment by w0lfschild** [comment]
As @Arketsu said Activedock is a seperate application that mimics the Dock. cDock injects code into the Dock to modify it.

**Comment by defrilitus** [comment]
My fault: I hadn't thought of this scenario. Pity. cDock is much better than ActiveDock. I upgraded to Mojave, but then downgraded as cDock wasn't available. It's one of my red lines. I will probably end up upgrading and keeping SIP disabled. Thanks for the replies.
