### ISSUE TITLE
cDock2 does not keep Theme configuration

### ISSUE THREAD

**Issue by abuyaqub** [w0lfschild/cDock2#164]
Greetings,
this is my second notice about the same problem. the clear glass theme does not seem to work. i have applied the theme, restarted cdock2 with no success. After trying other themes like transparent and then applying the "clear glass" theme it works.  However, after restarting my MAC the theme configuration is lost. Please advise.
Regardes
<img width="882" alt="screen shot 2018-10-07 at 8 09 46 am" src="https://user-images.githubusercontent.com/43880724/46581547-77027900-ca08-11e8-9e1c-80b34e509d33.png">
<img width="882" alt="screen shot 2018-10-07 at 8 11 21 am" src="https://user-images.githubusercontent.com/43880724/46581557-a0230980-ca08-11e8-9e8d-52e6cd2ee996.png">

**Comment by w0lfschild** [comment]
Most themes that use an image are for horizontal dock configuration only.
