### ISSUE TITLE
Finder Restarting when Switching between Dark/Light modes

### ISSUE THREAD

**Issue by recuerom** [w0lfschild/cDock2#167]
When I switch between Dark and Light modes in Mojave the Finder is being restarted which, in my case causes me to have to restart TotalFinder (Finder plug in).

I am wondering if anyone here is using CDOCK and TotalFinder and seeing the same problem. I am working with BinaryAge on this so not treating this as a CDOCK (or SIMBL) issue. The mode switch does NOT affect Cdock, just wondering if there is a conflict with TF.

Thanks...

PS Also using Bartender and Default Folder X.

**Comment by w0lfschild** [comment]
I don't think this should be related to cDock. Code is only loaded into the dock and not Finder.

**Comment by recuerom** [comment]
Found the problem..... Default Folder X optionally adds a button to the Finder Toolbar and it generates a Finder restart every time you switch modes. Turned off and all good !
