### ISSUE TITLE
Transparent dock

### ISSUE THREAD

**Issue by thearesat** [w0lfschild/cDock2#169]
I can't get the transparent to work on my dock.  I had it working but then shut off my computer and now I can't get it to work

**Comment by w0lfschild** [comment]
Try re-opening cDock and re-applying?

If you've updated to Mojave then you need to disable System Integrity protection.

**Comment by scottyofeden** [comment]
Is the fix to keep csrutil disabled ALL the time? Or is this suggestion only to apply the transparency, and then turn csrutil back on?

**Comment by w0lfschild** [comment]
Yes, on Mojave and above it needs to stay off.
