### ISSUE TITLE
Mojave: Finder context menu shows all open tabs rather than open windows

### ISSUE THREAD

**Issue by Davi-T** [w0lfschild/cDock2#170]
Not entirely sure if this is related to cDock but I'd imagine it is. Everything was working fine on the previous version of OSX and cDock but once I upgraded to Mojave (v10.14), cDock no longer works properly (I'm on cDock v1.2.0 (5752)). One of the other issues that now occurs is when I right click on the Finder icon in the dock to show the existing windows I have open. Previously, it would only show the Active tab within a main single Finder window (a 'window' being a single file browser and any tabs attached to it)– how it should work. Right now, when I right click on the Finder icon, it lists ALL the open TABS rather than just the main file browser windows. This gets real confusing if I have folders with the same name. See attached screenshot for what I am talking about.

Restarting the finder and dock does not resolve the issue.

![cdock_bug_101518](https://user-images.githubusercontent.com/20928342/46972165-e709a280-d08b-11e8-9f14-6750d25714f1.jpg)

**Comment by w0lfschild** [comment]
This is default behavior in Mojave and would happen with or without cDock installed.
