### ISSUE TITLE
cDock2 theme don't work

### ISSUE THREAD

**Issue by abuyaqub** [w0lfschild/cDock2#171]
setting cDock2 to clear glass does not work. i have tried changing it to default moving the dock to the default position with no success. 
<img width="585" alt="screen shot 2018-10-18 at 8 00 53 am" src="https://user-images.githubusercontent.com/43880724/47152956-20b8f400-d2ac-11e8-9b5e-7de370b1f90b.png">

**Comment by w0lfschild** [comment]
Unfortunately new security changes in 10.14 (Mojave) prevent cDock from working without System Integrity Protection Disabled.

You may try running it with `csrutil enable --without debug --without fs` to have partial SIP protection.

It is unlikely that there will be a workaround for this change.
