### ISSUE TITLE
have install cdock 3 on Mac os Mojave but doesn't themed. SIP is disable.

### ISSUE THREAD

**Issue by rajesh1108** [w0lfschild/cDock2#172]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by w0lfschild** [comment]
Do you see these files / folders installed on your system?

/System/Library/ScriptingAdditions/SIMBL.osax
/Library/Application Support/SIMBL/Plugins/cDock.bundle
~/Library/Application Support/cDock

**Comment by scottyofeden** [comment]
rajesh1108... Did you ever get a fix for this? I'm having a similar issue. Any changes I make in "Dock Settings" works fine after I click on 'Apply Changes and Restart'. 

However, there is no effect when making changes to 'themes' or any other option under the "Customize" tab. I've disabled csrutil, I've restarted my computer, I've applied and restarted the dock... nothing : (.
