### ISSUE TITLE
Liscense not working

### ISSUE THREAD

**Issue by pyrophire** [w0lfschild/cDock2#173]
**Describe the bug**
After upgrading to Mojave, cDock no longer recognized the cDoc license from Paddle. Attempting to re-enter the address, an "Error" box shows up, with no details just "Error".

**To Reproduce**
1. Open cDock
2. Click on Enter License 
3. Enter Email and Key and click Activate 

**Expected behavior**
Key to work and application to be activated

**Screenshots**
![screen shot 2018-10-19 at 3 06 50 pm](https://user-images.githubusercontent.com/3950831/47241266-b2118e80-d3b0-11e8-8279-61e05a7d9050.jpg)
![screen shot 2018-10-19 at 3 06 37 pm](https://user-images.githubusercontent.com/3950831/47241268-b3db5200-d3b0-11e8-8301-410249a85cb7.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Mojave

**Additional context**
Sent email to support, did not receive reply after 4 days.

**Comment by w0lfschild** [comment]
Sorry I'm the only support person and I've been rather busy lately. If I haven't replied to your email yet please send a new email.

**Comment by pyrophire** [comment]
I had to use AppCleaner to get the Error to go away. The license was fixed by support. Thanks!
