### ISSUE TITLE
Dock background is not transparent

### ISSUE THREAD

**Issue by Johnny-Kings** [w0lfschild/cDock2#174]
cDock 1.2.0 (5752)
MacOS Mojave 10.14 (18A391)

cDock theme set to transparent but dock background remains opaque white.
Sometimes it is possible to get the dock background transparent after several "restart dock" attempts.

**Comment by scottyofeden** [comment]
Did you find a fix for this? I'm having the same issue. If I play around with cDock with 'csrutil' disabled I can sometimes I get transparency to work for a minute. But not without csrutil disabled, which I'm not going to keep off for the sake of a transparent dock, even in the case if it works all the time.

**Comment by w0lfschild** [comment]
Mojave and beyond requires SIP to be off.
