### ISSUE TITLE
No 3D view of cDock

### ISSUE THREAD

**Issue by theobrinkman** [w0lfschild/cDock2#175]
Wolf

I bought the latest cDock from your site.
However I do not see cDock in 3D in Mojave
As you told me I have enabled crsutil
Please help to make cDock work again

regards
Theo

**Comment by w0lfschild** [comment]
``` bash
ls -al /Library/Application\ Support/SIMBL/Plugins | grep cDock; ls -al /System/Library/ScriptingAdditions | grep SIMBL;  ls -al ~/Library/Application\ Support/cDock | grep themes
```

If you open terminal and paste in the line from above and hit return what does it print out?

**Comment by theobrinkman** [comment]
Wolfgang

The following response has been given.
Does this help?


drwxr-xr-x  3 aurora  staff   96 30 sep 03:47 cDock.bundle

drwxr-xr-x    3 root  wheel    96 26 sep 18:59 SIMBL.osax

drwxr-xr-x   24 aurora  staff   768 28 okt 14:12 themes



Met vriendelijke groet,

Theo Brinkman


Van: Wolfgang Baird <notifications@github.com>
Beantwoorden - Aan: w0lfschild/cDock2 <reply@reply.github.com>
Datum: zondag 4 november 2018 om 02:46
Aan: w0lfschild/cDock2 <cDock2@noreply.github.com>
CC: Theo Brinkman <theobrinkman@outlook.com>, Author <author@noreply.github.com>
Onderwerp: Re: [w0lfschild/cDock2] No 3D view of cDock (#175)


ls -al /Library/Application\ Support/SIMBL/Plugins | grep cDock; ls -al /System/Library/ScriptingAdditions | grep SIMBL;  ls -al ~/Library/Application\ Support/cDock | grep themes

**Comment by theobrinkman** [comment]
Wolfgang

The following response has been printed out



drwxr-xr-x  3 aurora  staff   96 30 sep 03:47 cDock.bundle

drwxr-xr-x    3 root  wheel    96 26 sep 18:59 SIMBL.osax

drwxr-xr-x   24 aurora  staff   768 28 okt 14:12 themes



Met vriendelijke groet,

Theo Brinkman


Van: Wolfgang Baird <notifications@github.com>
Beantwoorden - Aan: w0lfschild/cDock2 <reply@reply.github.com>
Datum: zondag 4 november 2018 om 02:46
Aan: w0lfschild/cDock2 <cDock2@noreply.github.com>
CC: Theo Brinkman <theobrinkman@outlook.com>, Author <author@noreply.github.com>
Onderwerp: Re: [w0lfschild/cDock2] No 3D view of cDock (#175)


ls -al /Library/Application\ Support/SIMBL/Plugins | grep cDock; ls -al /System/Library/ScriptingAdditions | grep SIMBL;  ls -al ~/Library/Application\ Support/cDock | grep themes

If you open terminal and paste in the line from above and hit return what does it print out?

**Comment by theobrinkman** [comment]
Dear Wolfgang

I didn’t get any support on cDock. Please help.

Met vriendelijke groet,

Theo Brinkman


Van: Theo Brinkman <theobrinkman@outlook.com>
Datum: zondag 4 november 2018 om 16:51
Aan: w0lfschild/cDock2 <reply@reply.github.com>
Onderwerp: FW: [w0lfschild/cDock2] No 3D view of cDock (#175)

Wolfgang

The following response has been printed out



drwxr-xr-x  3 aurora  staff   96 30 sep 03:47 cDock.bundle

drwxr-xr-x    3 root  wheel    96 26 sep 18:59 SIMBL.osax

drwxr-xr-x   24 aurora  staff   768 28 okt 14:12 themes



Met vriendelijke groet,

Theo Brinkman


Van: Wolfgang Baird <notifications@github.com>
Beantwoorden - Aan: w0lfschild/cDock2 <reply@reply.github.com>
Datum: zondag 4 november 2018 om 02:46
Aan: w0lfschild/cDock2 <cDock2@noreply.github.com>
CC: Theo Brinkman <theobrinkman@outlook.com>, Author <author@noreply.github.com>
Onderwerp: Re: [w0lfschild/cDock2] No 3D view of cDock (#175)


ls -al /Library/Application\ Support/SIMBL/Plugins | grep cDock; ls -al /System/Library/ScriptingAdditions | grep SIMBL;  ls -al ~/Library/Application\ Support/cDock | grep themes

If you open terminal and paste in the line from above and hit return what does it print out?
