### ISSUE TITLE
[Request] Add Vertical Padding to Dock

### ISSUE THREAD

**Issue by benmeroff** [w0lfschild/cDock2#177]
Hello! I love this project and have been using cDock for a while now (years actually), and I was just wondering if there could be an option to add in vertical padding to the dock to increase the total height, adding space both above and below the dock icons. I added in a sort of manual top padding to my dock for a while by adding a thick top border the same color as my solid background, but with Mojave now I'm playing with using the Frost blur effect again and realized there is currently no other way to accomplish this. Any ideas?

**Comment by benmeroff** [comment]
Here's an example of what I'm mentioning:

![dock padding 1](https://user-images.githubusercontent.com/13946393/47752301-14e11080-dc62-11e8-8082-0f223d19d4e0.jpg)
Current (without Padding)

![dock padding 2](https://user-images.githubusercontent.com/13946393/47752308-1ad6f180-dc62-11e8-84a3-fc6719eab37b.jpg)
With Padding (exaggerated to show detail)

**Comment by InDoubt** [comment]
I second this request.
I made it previously, but in the wrong place :-(
So please: Would it be possible to add a Vertical Padding **control** to this application?
Thank you!
![no-marging-marging](https://user-images.githubusercontent.com/17437998/62828624-e614a500-bbb8-11e9-9a0d-f6728fdc2763.jpg)

**Comment by w0lfschild** [comment]
Not possible with my knowledge.
