### ISSUE TITLE
MacOS Mojave cDock does not work

### ISSUE THREAD

**Issue by Winsters** [w0lfschild/cDock2#179]
Works sometimes, but most times it does not. Have to click restart dock, etc. and maybe it'll apply my selected theme / preferences but most times not.

**Comment by scottyofeden** [comment]
Did you ever find or get a fix for this?

**Comment by Winsters** [comment]
Nope, have not used cDock this whole time
Because of it. 

Thanks for reaching out. Let me know action steps to resolve. Thanks

Cody Capeloto

**Comment by Winsters** [comment]
Please let me know what I need to do to actually have cDock work. I paid for cDock in November of last year, and it has been almost since then that I have not been able to use any of its functionalities. I am using Mojave. I have not heard response. Please at least let me know that you got this message and my previous one. I feel left in the dark here. Thanks. 


In Health, 

Cody Capeloto, D.C.
Doctor of Chiropractic

￼



      Website <http://www.rivercitywellnessatx.com/> - Facebook <http://www.facebook.com/rivercitywellness> - Instagram <http://www.instagram.com/rivercitywellnessatx>

       8708 S. Congress Ave Suite 570
                 Austin, TX 78745
                  512-535-4500
 
-

This e-mail transmission and any attachments that accompany it may
contain information that is privileged, confidential or otherwise
exempt from disclosure under applicable law and is intended solely
for the use of the individual(s) to whom it was intended to be addressed. 
If you have received this e-mail by mistake, or you are not the
intended recipient, any disclosure, dissemination, distribution,
copying or other use or retention of this communication or its
substance is prohibited.  If you have received this communication in
error, please immediately reply to the author via e-mail that you
received this message by mistake and also permanently delete the
original and all copies of this e-mail and any attachments from your
computer. Thank you.

On Dec 20, 2018, at 5:13 PM, scottyofeden <notifications@github.com> wrote:

Did you ever find or get a fix for this?

**Comment by scottyofeden** [comment]
What a shame! I was using cDock with High Sierra and it worked great. After upgrading to Mojave I received a notification from cDock that I would need to pay for it again. So I paid for it again. And it no longer worked. Not only that, but cDock knew it didn't work, and that they were not going to find a fix for it (by the sounds of it because they couldn't bypass Mac's security). So why was there no warning or some kind of notification stating that cDock would no longer work on Mojave+? Any why are they billing existing customers to upgrade when they know it won't work?

**Comment by w0lfschild** [comment]
cDock doesn't require a new purchase when you update. Maybe you used up all your license activations?
It does work on Mojave (at least most versions of) with SIP disabled.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/209
