### ISSUE TITLE
Weird black artifacting when I put my mouse over dock (MacOS Mojave)

### ISSUE THREAD

**Issue by Ackons** [w0lfschild/cDock2#186]
**Describe the bug**
Whenever I go over the dock with any theme enabled (including "none") it glitches and has weird black artifacting

**To Reproduce**
1. Apply any theme
2. Put mouse over dock

**Expected behavior**
Expected to be normal

**Screenshots**
<img width="1440" alt="screenshot 2018-11-28 at 4 34 07 pm" src="https://user-images.githubusercontent.com/24395436/49162587-782a9500-f32b-11e8-881a-9cbe787e6363.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14

**Comment by w0lfschild** [comment]
That looks like the Dock crashing if your whole wallpaper is going black (the Dock draws your wallpaper).
