### ISSUE TITLE
Crash when trying to hide applications

### ISSUE THREAD

**Issue by timbroder** [w0lfschild/cDock2#187]
**Describe the bug**

When trying to `Hide icons` I get a crash. Have tried with Spotify, Airmail, Mail, and Bear

**To Reproduce**
1. Open cDock
2. Click `Hide icons`
3. Click the `+`
4. Click `Spotify.app`
5. Click `Blacklist`

**Expected behavior**

The icon to disappear from the dock after a dock restart

**Screenshots**

![image](https://user-images.githubusercontent.com/121503/49248411-a2418d00-f3e7-11e8-9b74-3a0b1c29e02d.png)

**Desktop (please complete the following information):**
 - Mac OS: 10.14.1 (18B75)

**Additional context**

I'm currently running with SIP turned off as I just installed. About to reboot and see if that fixes it. Is there any other info I can provide?

Thanks!

**Comment by timbroder** [comment]
I was trying to set this up locally to try to pull more info (or fix it). Any idea why my instance looks like this?

![image](https://user-images.githubusercontent.com/121503/49525017-d4853b80-f87a-11e8-8e21-60fdc191dfdd.png)

**Comment by w0lfschild** [comment]
Not sure, maybe an accessibility setting is making it look like that?

**Comment by EpicOrange** [comment]
I've been having this issue on High Sierra (10.13.6), though the feature worked at some point (a few months ago maybe?)

**Comment by w0lfschild** [comment]
Should be fixed now.
