### ISSUE TITLE
cdock 0.10.1 crash

### ISSUE THREAD

**Issue by R-S-T** [w0lfschild/cDock2#19]
got the message of the new update being available. Installed, but on every attempt to start up the program, it crashes. This is on a MBPr 2014 running 10.10.5. 

Themes are still showing though...

regards
Ralf

**Comment by R-S-T** [comment]
Managed to solve the problem on the MBPr with deleting all associated cdock files and reinstalling.

But:
same problem on my MacPro (which never had the theming working). crash on every startup. No themes showing.
Deleting and reinstalling did not help here as it did on my MBPr.

**Comment by w0lfschild** [comment]
Yeah should be fixed with 0.10.2 I think.

**Comment by R-S-T** [comment]
Yup. 0.10.2. solved the crashing for me!
But still no themes....
