### ISSUE TITLE
cDock theming bug

### ISSUE THREAD

**Issue by PsyCoGeek** [w0lfschild/cDock2#194]
macOS v. 10.14.2 Mojave, 2018 MacBook Pro, Intel Core i9, 32Gb RAM, Intel UHD 630/Radeon Pro Vega 20 graphics.

cDock needs to be started, sometimes multiple times, and changes applied for resizing of standard indicators and fullscreen width dock changes to be applied. The dock is usually reverted to standard state when macOS is booted.

**Comment by jesusvallez** [comment]
https://github.com/w0lfschild/cDock2/issues/188

**Comment by nkk64** [comment]
Similar problems here. Started a while ago. Currently I'm on 10.14.4, MacBook Pro (Retina, 13-inch, Early 2015) Intel Iris Graphics. Usually needed couple of cDock restarts to apply theme (I use transparent). Today I have no luck - restarted both OS and cDock couple of times with no success.

**Comment by w0lfschild** [comment]
Check out version 3.04, hopefully this issue has been resolved.
