### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by halzahrani** [w0lfschild/cDock2#196]
it's not working at  all on macOS  10.14.3

**Comment by hansluyendijk** [comment]
It does work on my iMac, but strangely enough not on my MacBook Pro! I use Mojave 10.14.4...

**Comment by NormG1** [comment]
Agreed. Not working at all. 10.14.3. Nada. Clicking Restart Dock just beeps. 

Has the developer abandoned the program??

**Comment by nkk64** [comment]
For me sometimes it starts fine. Sometimes it won't. Clicking restart from theme settings usually helps after couple of restarts. Strange indeed. Mojave 10.14.3 on early 2015 Macbok pro.

**Comment by w0lfschild** [comment]
Do you have System Integrity Protection disabled?

**Comment by nkk64** [comment]
1. Booted to recovery to check csrutil status: yes, it's disabled
2. Booted to system - cDock did not theme (I use transparent mode)
3. Started cDock app to click "restart" - usually it helps but needs couple of tries - cDock did not theme even after 4th
4. Logged out and logged back in - sometimes that helps too. And YES it worked! 

Mojave 10.14.5

**Comment by w0lfschild** [comment]
Yeah I believe as of 10.14.5 the latest cDock doesn't work. Have to wait for me to get out an update.

https://github.com/w0lfschild/cDock2/issues/209
