### ISSUE TITLE
Stuck in Update loop from 0.9.11 to 10.12

### ISSUE THREAD

**Issue by ChapDaddy65** [w0lfschild/cDock2#20]
First time downloading and installing cDock2 and when I started the app up with SIP disabled, I keep getting update notifications asking me to update to 10.2 and the update never takes and keeps me on 9.11.

SIMBL is installed and working properly
SIP is disabled

OS: 10.11.3 (El Capitan)

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/21
