### ISSUE TITLE
Mojave 10.14.4

### ISSUE THREAD

**Issue by PRKrebs** [w0lfschild/cDock2#201]
Hi, 
I just updated to 10.14.4 and cDock seems to have stopped working all-together. SIP is disabled. Any changes to cDock have no effect after restarting dock. 
I rebooted twice no change ... just the default dock. 

Cheers,

Peter

**Comment by cburford1** [comment]
I have the same issue too running Mojave 10.14.4. SIP disabled does not seem to help to apply cDock changes. Hopefully an update will soon follow.

**Comment by Blue68Camaro** [comment]
Same issue here........... Nothing I change makes a difference, color, size you name it, let alone 3D working, main reason I purchased it. Now 10.13.6 still works on my older MAC but not 10.14.4.

**Comment by AdrenalineX** [comment]
Yes, same problem. Please fix!

**Comment by AdrenalineX** [comment]
Bump!

**Comment by PRKrebs** [comment]
Seems that the product is no longer supported. I'll throw it in the bin.
