### ISSUE TITLE
cDock2 not working properly in macOS Mojave

### ISSUE THREAD

**Issue by Johnny-Kings** [w0lfschild/cDock2#203]
Sometimes it works after reseting cDock several times. Most times it simply doesn't!
Serious malfunctioning and not getting fixed.
Why did I pay a license for this?

**Comment by AdrenalineX** [comment]
Same here!

**Comment by AdrenalineX** [comment]
Bump!

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/209
