### ISSUE TITLE
cDock 1.2.0 not applying on Mojave 10.14.5 Beta

### ISSUE THREAD

**Issue by MisterRDZ** [w0lfschild/cDock2#204]
This has been an ongoing issue, but restarting cDock several several times has always seemed to solve the problem. I just applied the most recent Mac OS beta and cDock will not apply the changes to the dock! :-(

**Comment by AdrenalineX** [comment]
I can confirm it's NOT working in Mojave!!

**Comment by AdrenalineX** [comment]
Bump!

**Comment by DoctorOctagonapus** [comment]
Can also confirm Cdock is unusable in Mojave. I can get it to display a 3D dock, but as soon as I move the mouse over it the dock crashes and restarts. Completely broke my dock.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/209
