### ISSUE TITLE
License not being accepted

### ISSUE THREAD

**Issue by meat-ball** [w0lfschild/cDock2#206]
I just replaced a dead Mac and trying to enter my license gives me an error. SIP is disabled and the program is working fine other than I'm still on the trial/can't activate my license. 
<img width="763" alt="cdock_error" src="https://user-images.githubusercontent.com/5460919/60410357-d5661d80-9b7c-11e9-8156-8c948b818359.png">

**Comment by meat-ball** [comment]
Hoping to get this resolved. My license isnt working

**Comment by meat-ball** [comment]
Down to 2 left on trial

**Comment by JayBrown** [comment]
Same here: https://github.com/w0lfschild/cDock2/issues/88#issuecomment-511831223

Maybe we first need to unregister cDock on the old computer? But that would mean: only a single license for one user on one computer? What the hell?!

**Comment by meat-ball** [comment]
> #88 (comment)
did you end up getting it resolved?

**Comment by w0lfschild** [comment]
@meat-ball 

Did you email support? If you email your email-address or license code to me I can reset it.

@JayBrown 

- Currently licenses are 2 uses each. 

- The seller I use (Paddle) has no way for the end user to manage their activations other than deactivating a currently active use. So if you get a new machine unfortunately you have to email support where the license can pretty easily be reset.

- On 3.0.4 and below uses are per account but with new changes in the Paddle sdk that just came out today on 3.0.5 activations will work for all accounts on a machine.

**Comment by meat-ball** [comment]
@w0lfschild I just sent you an email. Thanks

**Comment by w0lfschild** [comment]
@meat-ball  Done. Thanks for using cDock.

The newer Paddle SDK is supposed to show a new error message as well when you have run out of activations versus just throwing a blank error.

I'm gonna go ahead and close this issue for now.
