### ISSUE TITLE
Doesn't work with Catalina

### ISSUE THREAD

**Issue by r3volution11** [w0lfschild/cDock2#207]
cDock doesn't work with Catalina. I'm pretty sure SIMBL itself is not able to work itself.

Not sure how to modify the new system drive to get everything installed properly for cDock to work.

**Comment by NormG1** [comment]
Same problem. Says it needs to update files but does not appear to actually update the files because the pop-up appears on every launch. 

So at the moment, cDock is incompatible with Mac OSX 10.15 Catalina Public Beta.

**Comment by JayBrown** [comment]
Have you tried:

(1) disable SIP
(2) reboot with SIP disabled
(3) mount system volume as writable with `sudo mount -uw / && killall Finder`
(4) let cDock install its helper stuff
(5) reboot: SIP should still be disabled, but the system volume should now be read-only again, but with cDock's files in place

**Comment by r3volution11** [comment]
This appears to let cDock install its helper files but still no luck with it being effective.

**Comment by w0lfschild** [comment]
Yeah I don't think the current release version works on Catalina.

https://github.com/w0lfschild/cDock2/issues/209
