### ISSUE TITLE
cDock not working on 10.14.5 and above

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/cDock2#209]
Issue: cDock doesn't seem to be working with Catalina or the latest version of Mojave.

Just creating this issue and going to close all related issues with a link to here to clean up some issue clutter.

A working version of cDock will be out before Catalina goes live.

<img width="1500" alt="Screen Shot 2019-07-20 at 11 23 29 PM" src="https://user-images.githubusercontent.com/1920148/61587804-69f0e980-ab45-11e9-82eb-987a23a05365.png">

**Comment by NormG1** [comment]
Thanks for being responsive to users who love cDick. As you get closer to a solution, will you post betas here for test and comment? Will the Catalina compatible version be a paid upgrade?

**Comment by nkk64** [comment]
Meanwhile with 10.14.6 things got better. After system starts (and cDock does not load) all I have to do is run cDock.app and click 3-4 times 'Restart Dock' button and it does load. I rarely logout or restart system so I have to do it, say, once in a week or two. Quite workable. Hope it helps someone.

**Comment by jsteweii** [comment]
Thank you @w0lfschild for this awesome app and your continued support on it:-).

**Comment by cptkelevra** [comment]
So far, this works pretty reliably in 10.14.6, but test with Catalina beta fails completely. Please keep us posted on progress on that front and bless your heart for providing a fix for this one thing I felt was a glaring design error on Apple's part.

**Comment by NormG1** [comment]
I am using 1.2.0 with Catalina Beta 7 on a MacBook Pro. Happy to report it seems to be working.  But I notice there is a 3.0.3 version? Is this a beta version? When I click check for updates it tells me I am running the latest version at 1.2.0

**Comment by w0lfschild** [comment]
@NormG1 I took it down as I heard a few reports of it not applying.

If you're interested in checking it out, you can download it here: https://github.com/w0lfschild/app_updates/blob/master/cDock3/cDock.3.0.3.zip

**Comment by w0lfschild** [comment]
Alight 3.0.4 is out now and should fix this 👍

**Comment by jsteweii** [comment]
Thanks for this👍. One question though, SIP still needs to be disabled right?

-johnny

**Comment by w0lfschild** [comment]
@jsteweii 

Unfortunately yes, SIP off or partially off is required.

**Comment by jsteweii** [comment]
So, just to let you know, I've had it running on my Mojave system for around two weeks now and it's running perfectly. Thanks so much:-).

I won't be trying out Catalina in the foreseeable future since I have 32 bit apps i depend upon. Thanks again for your dedication.

-johnny

**Comment by nkk64** [comment]
It works well with Catalina too. Thanks
