### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by fabiobfava** [w0lfschild/cDock2#210]
Hello, I've got the license for cDock, and installed (and registered). I've also registered it on a Parallels Desktop Virtual Machine a few times, and now I can't register it again on my VM. I use to destroy the VM's and I confess I forgot to Un-Register it on the VM's, so now I can't register it anymore... Could be possible to erase all my registrations on your side and cDock asks again to register? I think I can register in more than one machine, thus I enable it on my VM's. Hope we can get it done, thanks! Cheers!

**Comment by w0lfschild** [comment]
Sorry for the slow response. I'm not sure if it's possible for a user to unregister a system they don't have access to with the current Paddle sdks. If they ever add that functionality I'll add it cDock ASAP but until then just use the support email.
