### ISSUE TITLE
cDock 3.0.1 customize not working

### ISSUE THREAD

**Issue by gabrielfsousa** [w0lfschild/cDock2#216]
after update to 3.0.1 customize wont work, just nothing on this section

**Comment by w0lfschild** [comment]
Interesting. I have a few questions:

1) What version of macOS?
2) Are you seeing any [crashes in the Console app](https://blog.macsales.com/45586-how-to-use-the-mac-console-app-to-diagnose-a-crash/)?
3) Do you see cDock Helper running in Activity Monitor?
4) Were you asked to enter your password after updating?
5) Do you have SIP off?

**Comment by gabrielfsousa** [comment]
1. 10.14.6
2. on user reports no cdock crashs
3.  i have cdocker helper running
4. wont rememebr
5. System Integrity Protection status: disabled.

**Comment by w0lfschild** [comment]
Does this file exist for you?

`/Library/Application Support/MacEnhance/Plugins/cDock.bundle`

**Comment by gabrielfsousa** [comment]
yes i have, version 3.0.3 works !! thanks
