### ISSUE TITLE
I upgraded to cDock 3.01 and now it doesn't work at all!

### ISSUE THREAD

**Issue by DilettanteDev** [w0lfschild/cDock2#217]
I upgraded to cDock 3.01 and now it doesn't work at all!  Before it only worked when I would launch the app after startup; I would restore the settings at startup, each and every day, hoping that you would put out a fix soon enough... but nope... now it just doesn't work at all.

Maybe, you'll remember me? I'm the person who sent you feedback and a screenshot about how your 'Dark Boot' app had an embedded trojan (Trojan.OSX.Pwnet).

Now I don't want my money back for cDock I just want the damn thing to work.

(Running Mojave 10.14.5 on a Mac Mini 2012 with 16GB ram)

**Comment by DilettanteDev** [comment]
{{ ALSO: cDock showed no crashes, SIP was fully disabled & there wasn't a password issue. }}

**Comment by w0lfschild** [comment]
Thanks for the report.

I pulled the update yesterday and I'm fairly certain I have a fix ready I'll try to roll out later today.

**Comment by gabrielfsousa** [comment]
thats good news !!!

**Comment by gabrielfsousa** [comment]
3.0.2 didnt solve the problem, theme wont work :(

**Comment by etrahretep** [comment]
Where do I download 3.03? V1.20 doesn't update...

**Comment by dockdude** [comment]
I am still running 1.2 and it's not automatically updating regardless of how many times I restarted cDock, how does one update to 3.0.3?

-dockdude

**Comment by etrahretep** [comment]
https://github.com/w0lfschild/app_updates/blob/master/cDock3/cDock.3.0.3.zip

**Comment by dockdude** [comment]
Thanks Peter. Updated and seems ok, except 3D clean doesn't work, has the theme location changed?

**Comment by cptkelevra** [comment]
1.2.0 has been stable on Mojave 10.14.6 for me, but have had no successes on Catalina public beta 6 on a parallels vm. 3.0.3 package you just linked worked immediately!!! Stress levels for upcoming update have just disappeared.

**Comment by dockdude** [comment]
Update: Theme started working after about 1 hour on 3.0.3. It may takes multiple restarts.

-dockdude

**Comment by DilettanteDev** [comment]
Sorry for that heated comment Wolfgang but I had been battling with cDock 1.20 for some time. Now the angels are singin'
Thanks finally for the fix!

Wolfgang Baird wrote:
 

Sent: Tuesday, September 03, 2019 at 1:51 AM

**Comment by w0lfschild** [comment]
Yeah sorry folks I pulled the 3.03 update because I wanted to do some more testing with the Helper Application and making sure it was installing the needed stuff for the new injection method. 

Not sure exactly what the issues people are having as this uses the same method as MacForge which I haven't had any helper issues reported for. cDock has a much larger user base though.
