### ISSUE TITLE
cDock 3.0.3 won't start without MacForge app

### ISSUE THREAD

**Issue by etrahretep** [w0lfschild/cDock2#218]
As described in the release notes version 3.0.3 should work without simble.
It only starts when using Macforge app. Is that the normal behavior?
Running 10.15 bèta (19A546d)

**Comment by w0lfschild** [comment]
Nope, should work on it's own.

Is the helper app crashing for you?

**Comment by etrahretep** [comment]
Got it working after cleaning all with appcleaner. This time i was asked to install the helperprogram.
Thanks!
