### ISSUE TITLE
Any way to add custom indicators

### ISSUE THREAD

**Issue by noshery** [w0lfschild/cDock2#22]
I've tried changing the indicator image files within themes but this doesn't seem to work. I've also tried MacUtil to no avail. Any way to use custom app indicator lights besides the ones provided? I was using MacUtil for cDock & recently updated to cDock 2.

**Comment by w0lfschild** [comment]
Look at an existing theme with custom indicators.

https://github.com/w0lfschild/cDock2/tree/master/cDock/cDock-GUI/themes/10.4
https://github.com/w0lfschild/cDock2/tree/master/cDock/cDock-GUI/themes/Fancy

You have to use the same filenames and have to have use image indicators option enabled.

**Comment by noshery** [comment]
Thanks! I tried it a couple of times yesterday but either the indicators disappeared or stayed the same. I'll try it again tonight and see if I can get this to work. May have just been a problem with cache.

**Comment by noshery** [comment]
I ended up switching back to the latest version of cDock & using MacUtil for indicators. The only thing I miss from v2 is the app label theme. I am ecstatic about the addition of a themed "List" view. I had themed the "Grid" view in the same way but could never find the associated resources for list view. I'm sure I could find the directory it in the source code. Did you just edit the associated png files or was it done another way?

**Comment by w0lfschild** [comment]
>The only thing I miss from v2 is the app label theme. I am ecstatic about the addition of a themed "List" view. I had themed the "Grid" view in the same way but could never find the associated resources for list view.

Not sure what you're asking about?
