### ISSUE TITLE
No longer works with Mac OS v15 Catalina Public Beta 8

### ISSUE THREAD

**Issue by NormG1** [w0lfschild/cDock2#221]
Was working fine in Beta 7, Apple's Beta 8 killed cDock entirely.

**Comment by cptkelevra** [comment]
using current public beta on parallels virtual with clock 3.0.3 and working properly.

**Comment by w0lfschild** [comment]
Yes please try this version:

https://github.com/w0lfschild/app_updates/blob/master/cDock3/cDock.3.0.3.zip?raw=true

**Comment by r3volution11** [comment]
I'm running 3.0.3 on latest Catalina beta and no luck. Still doesn't work for me.

**Comment by w0lfschild** [comment]
@r3volution11 is it crashing or something. Would need more info that just 'it's not working'.

It definitely works because I've been using it on Catalina throughout the whole beta period.

**Comment by r3volution11** [comment]
@w0lfschild Sorry, the app works but the dock does not change at all.

**Comment by w0lfschild** [comment]
@r3volution11 

* Is the helper actually running though?
* Were you prompted for you password after updating?
* Do you have SIP off?
* Any logs here `/Users/w0lf/Library/Logs/DiagnosticReports` ?

**Comment by r3volution11** [comment]
1. No
2. No
3. Yes
4. See attached.


[cDock Crash Logs 9-24-19.zip](https://github.com/w0lfschild/cDock2/files/3648427/cDock.Crash.Logs.9-24-19.zip)

**Comment by w0lfschild** [comment]
@r3volution11 Thanks!

Looks like the Helper is crashing because it's unable to load the sparkle framework.

Do you have cDock on an external hard drive and or is there anything out of the ordinary about your install location?

**Comment by r3volution11** [comment]
@w0lfschild Nope, it's in the default location (/Applications).

**Comment by w0lfschild** [comment]
@r3volution11 

Can you see if you're still having issues with the latest version [3.0.4](https://github.com/w0lfschild/app_updates/blob/master/cDock3/cDock.3.0.4.zip?raw=true)?

**Comment by r3volution11** [comment]
@w0lfschild Woohoo, it works! Thank you!

Just an FYI: When I opened it it asked for my password to install the helper. It did and reloaded the dock but nothing changed. I tried clicking "Apply Changes and Restart" a few times with no luck. I then quit the app and reopened it and it relaunched the dock with the changes.

**Comment by w0lfschild** [comment]
@r3volution11 

Excellent. Not 100% sure why the app needs to be restarted but at least it's working.

Probably going to push this as the live version soon, thanks for the replies.
