### ISSUE TITLE
[Enhancement] Monochrome dock icons

### ISSUE THREAD

**Issue by blueneogeo** [w0lfschild/cDock2#223]
Being able to set the saturation of the dock icons. This would make it easier to make the dock work with more minimalistic design setups.

**Comment by Brido-99** [comment]
I like the sound of this!

**Comment by w0lfschild** [comment]
This is probably something that could be done.

**Comment by w0lfschild** [comment]
I'll probably add a picker to choose from the options of `CICategoryColorEffect` from here [CoreImageFilterReference](https://developer.apple.com/library/archive/documentation/GraphicsImaging/Reference/CoreImageFilterReference/index.html)

![Screen Shot 2020-07-31 at 2 57 43 AM](https://user-images.githubusercontent.com/1920148/89024270-ac611080-d2d9-11ea-8fd5-b19d707daffc.png)

![Screen Shot 2020-07-31 at 3 02 02 AM](https://user-images.githubusercontent.com/1920148/89024629-41fca000-d2da-11ea-908f-20479c10317c.png)
