### ISSUE TITLE
cDock auf OS Catalina MacBook Pro 

### ISSUE THREAD

**Issue by harklein** [w0lfschild/cDock2#224]
Hallo,

ich kriege auf meinem Macbook mit dem Beta OS Catalina,
cDock nicht zum laufen.

Mit freundlichen Grüßen 

Harry Kleindienst

**Comment by w0lfschild** [comment]
Try updating to he latest version [3.0.4](https://github.com/w0lfschild/app_updates/blob/master/cDock3/cDock.3.0.4.zip?raw=true)
