### ISSUE TITLE
Can't hide icons

### ISSUE THREAD

**Issue by Brido-99** [w0lfschild/cDock2#225]
Running 3.04 on Mojave 10.14.6

When clicking on Hide Icons, then Blacklist to add an .app
nothing happens.

Regards!

**Comment by w0lfschild** [comment]
Have you tried restarting the Dock? Or are you not able to add apps to the list?

**Comment by Brido-99** [comment]
Restarting Dock has no effect. I'm unable to add apps to the list.

**Comment by etrahretep** [comment]
I'm getting this errror when trying to add apps (no matter what app...)

![Schermafbeelding 2019-10-01 om 11 21 03](https://user-images.githubusercontent.com/42773309/65950339-26b4d000-e43e-11e9-8884-3b65cc4dcc88.png)

**Comment by w0lfschild** [comment]
Okay. Thanks for the report! Fix will be out shortly.

**Comment by w0lfschild** [comment]
Bug should be fixed in 3.0.5
