### ISSUE TITLE
3.0.3 - 3.0.7

### ISSUE THREAD

**Issue by cptkelevra** [w0lfschild/cDock2#226]
very ecstatic to report stable functionality for me on last Catalina public beta and current official release!!!!

**Comment by luoshuhui** [comment]
> very ecstatic to report stable functionality for me on last Catalina public beta and current official release!!!!

3d mode is ok?

**Comment by cptkelevra** [comment]
Using “ black glass” theme

**Comment by w0lfschild** [comment]
Good to hear.
