### ISSUE TITLE
Keyboard Tab order is random

### ISSUE THREAD

**Issue by m-cerveny** [w0lfschild/cDock2#228]
Tab order is random and the first Tab is Hide Icons.
I use keyboard a lot and it's very confusing. Could it be reordered? See picture.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/11475311/66471293-5a6da680-ea8b-11e9-84cf-3118d2c3e871.png">

**Comment by w0lfschild** [comment]
I'll try to have a look at this soon.

What would be the expected behavior for you?

**Comment by m-cerveny** [comment]
> What would be the expected behavior for you?

Just from top to bottom, I guess. Thanks for considering.

**Comment by w0lfschild** [comment]
How do you select tabs with the keyboard in the first place? Is this an accessibility feature? I'm not sure how to reproduce this.
