### ISSUE TITLE
Dock icons too up high on Dock

### ISSUE THREAD

**Issue by allannyholm** [w0lfschild/cDock2#23]
With the latest release of cDock2 the icons are up too high on the Dock, making contact wit the top edge of the Dock. See image.

<img width="359" alt="cdock-icons" src="https://cloud.githubusercontent.com/assets/556558/12898612/f181d486-cead-11e5-9409-8f260aae2247.png">

**Comment by grahammiln** [comment]
See also [Ask Different: El Capitan dock and cdock 2 problem](http://apple.stackexchange.com/questions/226907/el-capitan-dock-and-cdock-2-problem/226911) where another user is reporting this behaviour.

**Comment by w0lfschild** [comment]
Reverted in 0.10.4
