### ISSUE TITLE
"Show indicators for open applications" re-enabled every time dock.app is restarted, regardless of settings in cDock or System Preferences 

### ISSUE THREAD

**Issue by kalafalas** [w0lfschild/cDock2#230]
"Show indicators for open applications" (the white dot under open applications) option is re-enabled every time dock.app is restarted, either manually, through cDock, or a reboot of the system, regardless of settings in cDock or System Preferences.

I like this feature disabled, but it keeps coming back on, even if I make sure to have it disabled in both the cdock app and system preferences.

thank you for such a cool app!

**Comment by w0lfschild** [comment]
Thanks, I'll look into this.
