### ISSUE TITLE
The app name color in the launchpad

### ISSUE THREAD

**Issue by Eternalzttz** [w0lfschild/cDock2#235]
When I used the clean theme, the app name color in the launchpad turned black, but the default color was white. I did not see this option in dock Settings. So how do I change the color to white?

**Comment by Eternalzttz** [comment]
cdock3.0.8&&Catalina

**Comment by w0lfschild** [comment]
I'll look into this, thanks for the report.

**Comment by Eternalzttz** [comment]
Wow, I don't know what happened, but it is normal now.
