### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by gpsdmsj1** [w0lfschild/cDock2#239]
Hi I do not have the 3d dock option in the drop down on my MacBook Pro. Please advise how to fix this. Thank you.

**Comment by w0lfschild** [comment]
There is no theme named "3D dock"

Several themes are "3D" 

- 10.5 - Leopard
- 10.8 - Mountain Lion
- Black Glass
- Brushed Metal
- Clean
- Clear Glass
- Graphite Bar
