### ISSUE TITLE
[Feature] Hide Applications

### ISSUE THREAD

**Issue by leo-fengchao** [w0lfschild/cDock2#24]
You know there are bunch of apps that only works in the background or don't have GUI, but they do have an icon on the dock. Could you please add a feature to hide those apps on the dock.

**Comment by w0lfschild** [comment]
Could potentially show up in the future. Probably not soon though. 

For now you can use [Dock Dodger](http://www.macupdate.com/app/mac/24427/dock-dodger).

**Comment by w0lfschild** [comment]
And as of 1.1.0 this feature is live.
