### ISSUE TITLE
Dock icon hover popover mask displays wrong

### ISSUE THREAD

**Issue by Quantumpanda** [w0lfschild/cDock2#241]
**Describe the bug**
The hover menus/popovers that display the icon titles when you hover over them have a black box knockout around them, as though their display mask were always visible. The knockout has the same dimensions as the popover, so it is visible in the rounded upper corners of the popover and also below the popover where the arrow comes out. Verified in both Light and Dark mode. This is not affected by the "Force Dark Menus" option.

**To Reproduce**
1. Have cDock Helper running as normal. The cDock configuration app does not need to be open.
2. Hover the pointer over any Dock icon.
3. Observe the incorrect popover mask.

**Expected behavior**
The popover mask should not be visible around the popover.

**Screenshots**
<img width="1792" alt="Hover Menus Issue - Dark" src="https://user-images.githubusercontent.com/6102262/71316364-abf7c180-243c-11ea-83c8-154991df33c9.png">
<img width="1792" alt="Hover Menus Issue - Light" src="https://user-images.githubusercontent.com/6102262/71316365-abf7c180-243c-11ea-904e-9125c5c4fe6e.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - Version: cDock 3.0.8

**Additional context**
While I would not expect "Force Dark Menus" to necessarily affect the appearance of these popovers, their appearance is affected by Dark or Light Mode, so it's not an unreasonable guess that the option might affect them.

**Comment by w0lfschild** [comment]
Do you have reduced transparency or any other settings like that on in accessibility in system preferences?

**Comment by Quantumpanda** [comment]
Hadn't thought to check that. The culprit appears to be "Increase contrast".
