### ISSUE TITLE
"Force Dark Menus" doesn't work

### ISSUE THREAD

**Issue by Quantumpanda** [w0lfschild/cDock2#242]
**Describe the bug**
Regardless of the "Force Dark Menus" setting in the cDock Dock Settings pane, Dock menus take on the appearance dictated by the system setting for Light Mode or Dark Mode. 

**To Reproduce**
1. Open System Preferences.
2. Click on General.
3. Select Light Mode.
4. Open the cDock configuration app (cDock.app).
5. Click on "Dock Settings".
6. If "Force Dark Menus" is checked, right-click on any Dock icon. If "Force Dark Menus" is not checked, click on it to check it, then restart the Dock, then right-click on any Dock icon.
7. Observe that the menu that appears is the normal Light Mode menu.

**Expected behavior**
When "Force Dark Menus" is checked and the system is in Light Mode, the Dock menus should appear as though the system were in Dark Mode.

**Screenshots**
<img width="1792" alt="Force Dark Menus" src="https://user-images.githubusercontent.com/6102262/71316592-f62e7200-243f-11ea-96f6-d5f40c8fea8c.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.2
 - Version: cDock 3.0.8

**Additional context**
I'm not sure whether "Force Dark Menus" should affect the icon title popovers, but if it should, they are similarly unaffected. I already opened a separate issue regarding an anomaly in the appearance of those popovers.

**Comment by w0lfschild** [comment]
Unfortunately not sure this is something I'll be able to fix. 

The feature has been hidden / removed from current versions of cDock as it doesn't work correctly.
