### ISSUE TITLE
cDock and mac 10.12.6 

### ISSUE THREAD

**Issue by herbst53** [w0lfschild/cDock2#243]
Something is going wrong, dear developers. When i use to customize my dock, nothing appears - nothing changed. I purchased cdock 3.0.8
Are you so Kind and can you help me. Please don't be angry about my very bad entlieh language knowledges....Greatings from Hennef, Micha

**Comment by w0lfschild** [comment]
Have you disabled System Integrity Protection?

**Comment by herbst53** [comment]
<!--
Mein Selektor {
	font-family: "Delius 400"
              
                
                  
                    
@import url('https://fonts.googleapis.com/css?family=Delius&display=swap');
 
                      
                        Thank you very much, Wolfgang,
                            now it works. I still have a question: How
                            can I make the cdock window disappear after
                            starting? Best regards, Michael
                        By the way: Do I always have
                            to write everything in English? Or can I
                            also write in German? My English skills are
                            pretty bad.
                        
                      
                    
                  
                
                
                  
                    
                      
                      
                    
                  
                
                
                  
                    
@import url('https://fonts.googleapis.com/css?family=Delius&display=swap');
 
                      Freundliche Grüße
                          aus Hennef
                          Michael
                            Frenzen
                              Seestraße 28
                          53773 Hennef
                          02242 – 9160766
                          
A:link {text-decoration: none; color:#566988}
A:visited {text-decoration: none; color:#566988}
A:active {text-decoration: none; color:#566988}
A:hover {text-decoration: none; color:#566988} words@web.de
                                www.macgraphics.de
                        
                       
                      
                    
                  
                
                
                
              
            
          
        
      
    
    Am 28.12.19 um 23:44 schrieb Wolfgang
      Baird:
    
    
      Have you disabled System Integrity Protection?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/w0lfschild/cDock2/issues/243?email_source=notifications\u0026email_token=AOERCZYBCZNHVUG2UQIWOZLQ27JDVA5CNFSM4KAOL6U2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYTREQ#issuecomment-569456786",
"url": "https://github.com/w0lfschild/cDock2/issues/243?email_source=notifications\u0026email_token=AOERCZYBCZNHVUG2UQIWOZLQ27JDVA5CNFSM4KAOL6U2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHYTREQ#issuecomment-569456786",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by w0lfschild** [comment]
Make sure the main app isn't in your login items 

System Preferences > Users & Groups > Login Items
