### ISSUE TITLE
cDock crazy behavior

### ISSUE THREAD

**Issue by coltrane58** [w0lfschild/cDock2#244]
Sorry if this is a repeat issue. I've sent an email regading this issue. I am running CDock 3.08 with High Sierra 10.13.6 with SIP disabled. 
I had to restore my system from a time machine backup and now things are a little wierd. When I start CDock the entire desktop continuously switches between a black desktop and the normal desktop with my desktop image. When I click on Restart Dock the switching stops. Also, CDock no longer modifies the Dock. The Dock is the system default dock and I can't change it. I tried to reinstall CDock but that didn't help. 
I'd appreciate any help, I love CDock and have been using it since Apple got rid of the 3D Dock. 
thanks
john

**Comment by w0lfschild** [comment]
The Dock actually Renders the desktop image. The black flashing is the Dock crashing and restarting itself over and over again. Do you have crash logs in the console app?

**Comment by coltrane58** [comment]
The following is from a search for “dock” in the system.log from the last time I had the problem.

 

Jan  2 15:51:00 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100007.Aqua): com.apple.Dock.agent (lint): The HideUntilCheckIn property is an architectural performance issue. Please transition away from it.

Jan  2 15:51:04 Johns-Mac-mini com.apple.dock.extra[629]: objc[629]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11e6979a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11e837748). One of the two will be used. Which one is undefined.

Jan  2 15:51:16 Johns-Mac-mini com.w0lf.cDock.Injector[753]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?

Jan  2 15:51:16 Johns-Mac-mini com.apple.xpc.launchd[1] (com.w0lf.cDock.Injector[753]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.w0lf.cDock.Injector.mach

Jan  2 15:51:17 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[601]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:18 Johns-Mac-mini com.apple.dock.extra[772]: objc[772]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1217959a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x121935748). One of the two will be used. Which one is undefined.

Jan  2 15:51:18 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[768]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:20 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[775]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:20 Johns-Mac-mini com.apple.dock.extra[786]: objc[786]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11b84d9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11b9ed748). One of the two will be used. Which one is undefined.

Jan  2 15:51:21 Johns-Mac-mini com.apple.dock.extra[795]: objc[795]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11684e9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1169ee748). One of the two will be used. Which one is undefined.

Jan  2 15:51:21 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[793]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:23 Johns-Mac-mini com.apple.dock.extra[802]: objc[802]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11f87f9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11fa1f748). One of the two will be used. Which one is undefined.

Jan  2 15:51:23 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[796]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:24 Johns-Mac-mini com.apple.dock.extra[809]: objc[809]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x111d669a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x111f06748). One of the two will be used. Which one is undefined.

Jan  2 15:51:25 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[803]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

Jan  2 15:51:26 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[811]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:32 Johns-Mac-mini com.apple.dock.extra[824]: objc[824]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1193cd9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11956d748). One of the two will be used. Which one is undefined.

Jan  2 15:51:33 Johns-Mac-mini com.w0lf.cDock.Injector[826]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?

Jan  2 15:51:33 Johns-Mac-mini com.apple.xpc.launchd[1] (com.w0lf.cDock.Injector[826]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.w0lf.cDock.Injector.mach

Jan  2 15:51:33 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[815]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:35 Johns-Mac-mini com.apple.dock.extra[837]: objc[837]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11f1849a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11f324748). One of the two will be used. Which one is undefined.

Jan  2 15:51:35 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[831]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:37 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[840]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:37 Johns-Mac-mini com.apple.dock.extra[843]: objc[843]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x121f079a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1220a7748). One of the two will be used. Which one is undefined.

Jan  2 15:51:38 Johns-Mac-mini com.apple.dock.extra[846]: objc[846]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1169d89a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x116b78748). One of the two will be used. Which one is undefined.

Jan  2 15:51:38 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[844]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:40 Johns-Mac-mini com.apple.dock.extra[849]: objc[849]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1260ce9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x12626e748). One of the two will be used. Which one is undefined.

Jan  2 15:51:40 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[847]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:41 Johns-Mac-mini com.apple.dock.extra[852]: objc[852]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1198619a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x119a01748). One of the two will be used. Which one is undefined.

Jan  2 15:51:41 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[850]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:43 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[856]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:44 Johns-Mac-mini com.apple.dock.extra[858]: objc[858]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11c5259a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11c6c5748). One of the two will be used. Which one is undefined.

Jan  2 15:51:45 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[859]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:46 Johns-Mac-mini com.apple.dock.extra[869]: objc[869]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1151d39a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x115373748). One of the two will be used. Which one is undefined.

Jan  2 15:51:46 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[864]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:47 Johns-Mac-mini com.apple.dock.extra[872]: objc[872]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11a4dc9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11a67c748). One of the two will be used. Which one is undefined.

Jan  2 15:51:48 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[871]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:49 Johns-Mac-mini com.apple.dock.extra[874]: objc[874]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11d6489a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11d7e8748). One of the two will be used. Which one is undefined.

Jan  2 15:51:49 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[873]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:50 Johns-Mac-mini com.apple.dock.extra[877]: objc[877]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11b1689a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11b308748). One of the two will be used. Which one is undefined.

Jan  2 15:51:50 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[876]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:52 Johns-Mac-mini com.apple.dock.extra[882]: objc[882]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11bc859a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11be25748). One of the two will be used. Which one is undefined.

Jan  2 15:51:52 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[880]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

Jan  2 15:51:53 Johns-Mac-mini com.apple.dock.extra[887]: objc[887]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1154d59a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x115675748). One of the two will be used. Which one is undefined.

Jan  2 15:51:54 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[884]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:55 Johns-Mac-mini com.apple.dock.extra[892]: objc[892]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1236089a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1237a8748). One of the two will be used. Which one is undefined.

Jan  2 15:51:55 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[888]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:51:57 Johns-Mac-mini com.apple.dock.extra[896]: objc[896]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11df4d9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11e0ed748). One of the two will be used. Which one is undefined.

Jan  2 15:51:57 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[893]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:58 Johns-Mac-mini com.apple.dock.extra[899]: objc[899]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11746c9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11760c748). One of the two will be used. Which one is undefined.

Jan  2 15:51:58 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[897]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:51:59 Johns-Mac-mini com.apple.dock.extra[904]: objc[904]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1171d09a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x117370748). One of the two will be used. Which one is undefined.

Jan  2 15:52:00 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[903]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:01 Johns-Mac-mini com.apple.dock.extra[906]: objc[906]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11c9209a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11cac0748). One of the two will be used. Which one is undefined.

Jan  2 15:52:01 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[905]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:02 Johns-Mac-mini com.apple.dock.extra[910]: objc[910]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11f7c89a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11f968748). One of the two will be used. Which one is undefined.

Jan  2 15:52:02 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[907]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:04 Johns-Mac-mini com.apple.dock.extra[912]: objc[912]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11579c9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11593c748). One of the two will be used. Which one is undefined.

Jan  2 15:52:04 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[911]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:05 Johns-Mac-mini com.apple.dock.extra[914]: objc[914]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1220a09a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x122240748). One of the two will be used. Which one is undefined.

Jan  2 15:52:05 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[913]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:07 Johns-Mac-mini com.apple.dock.extra[919]: objc[919]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11b18f9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11b32f748). One of the two will be used. Which one is undefined.

Jan  2 15:52:07 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[916]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:08 Johns-Mac-mini com.apple.dock.extra[922]: objc[922]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11d0b89a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11d258748). One of the two will be used. Which one is undefined.

Jan  2 15:52:08 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[920]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

Jan  2 15:52:10 Johns-Mac-mini com.apple.dock.extra[928]: objc[928]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1241e99a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x124389748). One of the two will be used. Which one is undefined.

Jan  2 15:52:10 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[923]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:11 Johns-Mac-mini com.apple.dock.extra[930]: objc[930]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x118e909a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x119030748). One of the two will be used. Which one is undefined.

Jan  2 15:52:11 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[929]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:12 Johns-Mac-mini com.apple.dock.extra[932]: objc[932]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11ea209a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11ebc0748). One of the two will be used. Which one is undefined.

Jan  2 15:52:13 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[931]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

Jan  2 15:52:14 Johns-Mac-mini com.apple.dock.extra[935]: objc[935]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11772a9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1178ca748). One of the two will be used. Which one is undefined.

Jan  2 15:52:14 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[933]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:15 Johns-Mac-mini com.apple.dock.extra[940]: objc[940]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1215ba9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x12175a748). One of the two will be used. Which one is undefined.

Jan  2 15:52:16 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[937]): Service exited due to signal: Illegal instruction: 4 sent by exc handler[0]

Jan  2 15:52:17 Johns-Mac-mini com.apple.dock.extra[944]: objc[944]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x123ea49a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x124044748). One of the two will be used. Which one is undefined.

Jan  2 15:52:17 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[942]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:18 Johns-Mac-mini com.apple.dock.extra[951]: objc[951]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11363f9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1137df748). One of the two will be used. Which one is undefined.

Jan  2 15:52:18 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[948]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:20 Johns-Mac-mini com.apple.dock.extra[954]: objc[954]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11cce19a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11ce81748). One of the two will be used. Which one is undefined.

Jan  2 15:52:20 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[953]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:21 Johns-Mac-mini com.apple.dock.extra[957]: objc[957]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x112f169a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1130b6748). One of the two will be used. Which one is undefined.

Jan  2 15:52:21 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[955]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:23 Johns-Mac-mini com.apple.dock.extra[959]: objc[959]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x1136539a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1137f3748). One of the two will be used. Which one is undefined.

Jan  2 15:52:23 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[958]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:24 Johns-Mac-mini com.apple.dock.extra[961]: objc[961]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11780b9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1179ab748). One of the two will be used. Which one is undefined.

Jan  2 15:52:25 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[960]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:26 Johns-Mac-mini com.apple.dock.extra[964]: objc[964]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11c91f9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11cabf748). One of the two will be used. Which one is undefined.

Jan  2 15:52:26 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[962]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:27 Johns-Mac-mini com.apple.dock.extra[966]: objc[966]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11674d9a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x1168ed748). One of the two will be used. Which one is undefined.

Jan  2 15:52:28 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[965]): Service exited due to signal: Segmentation fault: 11 sent by exc handler[0]

Jan  2 15:52:29 Johns-Mac-mini com.apple.dock.extra[969]: objc[969]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x118ba39a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x118d43748). One of the two will be used. Which one is undefined.

Jan  2 15:52:29 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[968]): Service exited due to signal: Bus error: 10 sent by exc handler[0]

Jan  2 15:52:31 Johns-Mac-mini com.apple.dock.extra[973]: objc[973]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11fe309a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11ffd0748). One of the two will be used. Which one is undefined.

Jan  2 15:52:31 Johns-Mac-mini com.apple.xpc.launchd[1] (com.apple.Dock.agent[970]): Service exited due to signal: Killed: 9 sent by killall[974]

Jan  2 15:52:33 Johns-Mac-mini com.apple.dock.extra[976]: objc[976]: Class AMSupportURLConnectionDelegate is implemented in both /System/Library/PrivateFrameworks/OSPersonalization.framework/Versions/A/OSPersonalization (0x11b9589a0) and /System/Library/PrivateFrameworks/EmbeddedOSInstall.framework/Versions/A/EmbeddedOSInstall (0x11baf8748). One of the two will be used. Which one is undefined.

Jan  2 15:53:54 Johns-Mac-mini Dock[975]: DEPRECATED USE in libdispatch client: Setting timer interval to 0 requests a 1ns timer, did you mean FOREVER (a one-shot timer)?

Jan  2 15:57:31 Johns-Mac-mini Dock[975]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked

**Comment by coltrane58** [comment]
I’ve attached a crash log. Don’t know if it will help.

Also, I booted into safe mode and the dock/desktop was fine.

**Comment by coltrane58** [comment]
Just to let you know, when I re-enabled SIP the Dock stopped crashing. It also stops crashing either when I restart the Dock in CDock or if I perform a killall KILL Dock. 

 

regards
