### ISSUE TITLE
3.0.9 crashing Dock

### ISSUE THREAD

**Issue by Quantumpanda** [w0lfschild/cDock2#248]
After installing the 3.0.9 update to cDock today on my 16" 2019 MBP running macOS Catalina 10.15.2, I'm getting Dock crashes when I try to select themes or apply some settings. What generally happens is that I'll change one setting, and it takes. Then I'll change another setting, and it won't take. I'll then either change a third setting, or restart the Dock, then change a third setting, and at this point Dock crashes. cDock then cannot make changes without crashing the Dock until I quit cDock Helper from Activity Monitor.

I have attached a concatenated copy of three consecutive crash logs.
[Dock_crash_logs.txt](https://github.com/w0lfschild/cDock2/files/4106204/Dock_crash_logs.txt)

**Comment by mlmilliman** [comment]
Same here.

**Comment by w0lfschild** [comment]
Can you upload a .zip of your crash logs and your current cDock settings?

`~/Library/Logs/DiagnosticReports` < Crash reports
`~/Library/Preferences/org.w0lf.cDock.plist` < cDock settings
`~/Library/Application Support/cDock/themes/*/*.plist` < Theme settings

**Comment by mlmilliman** [comment]
Dear Wolfgang:

I reverted back to 3.0.8 because of the issues with 3.0.9. I zipped the files you requested anyway. Let me know if it was of some use.

Thanks for working on this issue,
Mark
Mark Milliman
Boulder, CO
mlmilliman@gmail.com <mailto:mlmilliman@gmail.com>

**Comment by w0lfschild** [comment]
@mlmilliman 

Can you send them to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.

You can reach me at: support@macenhance.com
