### ISSUE TITLE
cDock 3.0.9 does not hide applications

### ISSUE THREAD

**Issue by wsfreund** [w0lfschild/cDock2#249]
**Describe the bug**
Just updated cDock to version 3.0.9, the hide apps feature is not working anymore.

**To Reproduce**
1. Have cDock 3.0.8 installed (Catalina, latest update)
2. Update to 3.0.9
3. No more hidden apps

**Expected behavior**
Have hidden apps after updating :(

**Desktop (please complete the following information):**
 - OS: Catalina
 - Version 10.15.2

**Additional context**
Everything else seems to be fine, just that I cannot have hidden apps anymore.

**Comment by zqso** [comment]
Yes, I have the same problem.
cDock 3.0.8 works,
cDock 3.0.9 does not.

**Comment by zqso** [comment]
Yes, I have the same problem.
cDock 3.0.8 works,
cDock 3.0.9 does not.

**Comment by w0lfschild** [comment]
I'll have this fixed in the next update, sorry about that.

**Comment by w0lfschild** [comment]
Can you please try this build: [cDock v3.1.0](https://github.com/w0lfschild/app_updates/raw/master/test/cDock.3.1.0.zip)

**Comment by wsfreund** [comment]
It solved the problem! Many thanks!
