### ISSUE TITLE
cDock Helper not signed(?)

### ISSUE THREAD

**Issue by herbs** [w0lfschild/cDock2#25]
Howdy,

I start up cDock at login. I'm now getting dialog boxes at startup that basically say that cDock Helper is not signed. I have to manually go to the General tab of System Preferences->Security & Privacy and tell it to load. I have it set for App Store and Signed apps.

Good Luck,
Herb Schulz

**Comment by herbs** [comment]
Howdy,

Sorry, I should have added: OS X 10.11.3, cDock2 0.10.4. I was previously using cDock2 0.10.2 with no problems. The dialog box and requirement to go to System Preferences->Security & Privacy happens on every login; if it only happened once this wouldn't bother me.

Good Luck,
Herb Schulz

**Comment by w0lfschild** [comment]
Maybe try right clicking the helper and choosing open.

**Comment by herbs** [comment]
> On Mar 10, 2016, at 9:10 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> Maybe try right clicking the helper and choosing open.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Howdy,

I'll have to check that the next time. I ended up allowing all apps to run; rebooted and was asked if it was ok to run the app; changed it back to only run signed apps and haven't had a problem since. I'm guessing that procedure allowed the quarantine bit to get reset.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by w0lfschild** [comment]
I decided I would fork over the $100 dollars to Apple and bought a developer account so from now on out all my Apps ([cDock](https://github.com/w0lfschild/cDock2), [Dark Boot](https://github.com/w0lfschild/DarkBoot), [mySIMBL](https://github.com/w0lfschild/mySIMBL)) will be code-signed and any helper tools should be signed as well.

**Comment by herbs** [comment]
> On May 8, 2016, at 12:02 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> I decided I would fork over the $100 dollars to Apple and bought a developer account so from now on out all my Apps (cDock, Dark Boot, mySIMBL) will be code-signed and any helper tools should be signed as well.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

Howdy,

Thanks for the information.

Just curious... will you be coming out with an update to cDock that uses mySimbl so there won't be a need to use SIMBL?

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by w0lfschild** [comment]
No. mySIMBL uses (SIMBL) the same install process as cDock. Basically with the introduction of System Integrity Protection anything like cDock that's injecting into system apps will require SIP to be disabled at least once.

DockMod tried to get around this with an signed Kernel Extension but that only lasted like a month before Apple revoked their signature and add the extension to their Malware list.

http://www.macupdate.com/app/mac/51114/dockmod
http://enterprisemac.bruienne.com/2016/03/04/kext-friends-forever/
