### ISSUE TITLE
Bug: Saving Preferences 

### ISSUE THREAD

**Issue by NormG1** [w0lfschild/cDock2#251]
Clicking Save and Restart Dock button on the Dock Setting screen is supposed to add that saved setting to the TOP of the list. The Newest first, oldest at the bottom.

It doesn't work that way. Saves the most recent setting as the second setting in the list and all subsequent settings are added into position #2 in the list, not position #1 as in past versions.

**Comment by w0lfschild** [comment]
The list was actually never sorted in previous versions...

If it used to appear sorted to you it was nearly coincidence.

```objectivec
NSArray* dirs = [FileManager contentsOfDirectoryAtPath:backFldr error:Nil];
NSArray* plists = [dirs filteredArrayUsingPredicate:[NSPredicate predicateWithFormat:@"self ENDSWITH '.plist'"]];
NSMenu *fileMenu = [[NSMenu alloc] init];
if ([plists count]) {
    [_dock_selectedBackup setEnabled:true];
    for (NSString *file in plists)
        [fileMenu addItem:[[NSMenuItem alloc] initWithTitle:file action:nil keyEquivalent:@""]];
} else {
    [_dock_selectedBackup setEnabled:false];
    [fileMenu addItem:[[NSMenuItem alloc] initWithTitle:@"No Backups Found" action:nil keyEquivalent:@""]];
}
[_dock_selectedBackup setMenu:fileMenu];
```

Maybe I'll try to sort it in the future.
