### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by pruznick** [w0lfschild/cDock2#252]
I dowloaded and installed cDock v3.0.9 on my MacBook Pro in 10.14.6 and it messed up my computer. Every time I move the cursor down to the dock, it flashes the desktop to black. The dock doesn't work anymore. I've tried turning the themes off and restarting, tried uninstalling the software and restarting, but nothing fixes it. 

Can you please send me a code to put into Terminal to remove the changes your software did to my system?

**Comment by w0lfschild** [comment]
`rm -rf /Library/Application\ Support/MacEnhance/Plugins/cDock.bundle; killall Dock`

**Comment by pruznick** [comment]
That's not working. The command makes my desktop flash off and back on, but
the problem is persisting. I've uninstalled cDock and restarted but no luck.

**Comment by pruznick** [comment]
Actually, after restarting, the dock works for about 2 seconds—it functions normally with the default appearance. But then cDock somehow kicks in and causes the desktop to flash, then the persistent crashing resumes (incidentally, when you can see the dock before it crashes, it has a 3D appearance—like cDock is still running somehow). I've uninstalled cDock and executed the Terminal code you provided, so I have no idea how your software is still modifying my system.

**Comment by w0lfschild** [comment]
Open the Folder in Finder and try deleting the bundle?

**Comment by pruznick** [comment]
That seems to have worked! I had done a spotlight search for cDock and
deleted everything that came up, but I didn't focus it on the Library.
That's where I found the bundle.

Thanks for working with me on this! And please let me know if this issue
might be resolved in future iterations, because I really would like to use
the software.

**Comment by dbp1960** [comment]
I have had the same problem with 10.14.6. I was able to get it working and stabilize the dock by going to security & privacy removing permission for cdock.app and SIMBLAgent.app|Dock exiting to system preferences and then going to security & privacy and adding permission for cdock.app and SIMBLAgent.app|Dock again.
