### ISSUE TITLE
Catalina bag

### ISSUE THREAD

**Issue by manijak1** [w0lfschild/cDock2#253]
When adding a tag folder with programs to the dock, the dock is constantly reloaded and the folder does not open. This also restarts finder. I wrote to you in the mail, but there is no answer. Can I fix this problem? OS Catalina 10.15.3 Mac book pro 16'
BRGDS

**Comment by w0lfschild** [comment]
Can you upload a .zip of your crash logs and your current cDock settings?

`~/Library/Logs/DiagnosticReports` < Crash reports
`~/Library/Preferences/org.w0lf.cDock.plist` < cDock settings
`~/Library/Application Support/cDock/themes/*/*.plist` < Theme settings

**Comment by manijak1** [comment]
Of course.

 

От: Wolfgang Baird <notifications@github.com>
Обратный адрес: w0lfschild/cDock2 <reply@reply.github.com>
Дата: суббота, 14 марта 2020 г. в 10:21
Кому: w0lfschild/cDock2 <cDock2@noreply.github.com>
Копия: Алексей Володин <mv.president1@mail.ru>, Author <author@noreply.github.com>
Тема: Re: [w0lfschild/cDock2] Catalina bag (#253)

 

Can you upload a .zip of your crash logs and your current cDock settings?

~/Library/Logs/DiagnosticReports < Crash reports
~/Library/Preferences/org.w0lf.cDock.plist < cDock settings
~/Library/Application Support/cDock/themes/*/*.plist < Theme settings

**Comment by manijak1** [comment]
Just send to you logs ang settings. In 3.0.7 this problem missing…

 

От: Wolfgang Baird <notifications@github.com>
Обратный адрес: w0lfschild/cDock2 <reply@reply.github.com>
Дата: суббота, 14 марта 2020 г. в 10:21
Кому: w0lfschild/cDock2 <cDock2@noreply.github.com>
Копия: Алексей Володин <mv.president1@mail.ru>, Author <author@noreply.github.com>
Тема: Re: [w0lfschild/cDock2] Catalina bag (#253)

 

Can you upload a .zip of your crash logs and your current cDock settings?

~/Library/Logs/DiagnosticReports < Crash reports
~/Library/Preferences/org.w0lf.cDock.plist < cDock settings
~/Library/Application Support/cDock/themes/*/*.plist < Theme settings

**Comment by w0lfschild** [comment]
@manijak1   

1) Can you please try this build: [cDock v3.1.0](https://github.com/w0lfschild/app_updates/raw/master/test/cDock.3.1.0.zip)

2) If the issue persists can you re-send your crash logs and preferences zip to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.

You can reach me at: support@macenhance.com

**Comment by manijak1** [comment]
Ok. I try

 

От: Wolfgang Baird <notifications@github.com>
Обратный адрес: w0lfschild/cDock2 <reply@reply.github.com>
Дата: понедельник, 16 марта 2020 г. в 14:01
Кому: w0lfschild/cDock2 <cDock2@noreply.github.com>
Копия: Алексей Володин <mv.president1@mail.ru>, Mention <mention@noreply.github.com>
Тема: Re: [w0lfschild/cDock2] Catalina bag (#253)

 

@manijak1
Can you please try this build: cDock v3.1.0
If the issue persists can you re-send your crash logs and preferences zip to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.
You can reach me at: support@macenhance.com

**Comment by manijak1** [comment]
Same problem…

 

От: Wolfgang Baird <notifications@github.com>
Обратный адрес: w0lfschild/cDock2 <reply@reply.github.com>
Дата: понедельник, 16 марта 2020 г. в 14:01
Кому: w0lfschild/cDock2 <cDock2@noreply.github.com>
Копия: Алексей Володин <mv.president1@mail.ru>, Mention <mention@noreply.github.com>
Тема: Re: [w0lfschild/cDock2] Catalina bag (#253)

 

@manijak1
Can you please try this build: cDock v3.1.0
If the issue persists can you re-send your crash logs and preferences zip to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.
You can reach me at: support@macenhance.com

**Comment by w0lfschild** [comment]
@manijak1   

1) Can you re-send your crash logs and preferences zip to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.

2) Does the issue persist if you turn off icon reflections?

You can reach me at: support@macenhance.com
