### ISSUE TITLE
Catalina not working properly!.when click a download folder or Drive

### ISSUE THREAD

**Issue by jeweljitu** [w0lfschild/cDock2#255]
When i click a download or drive folder dock to restart my build in one. later not working. i am disappointed coz spend 5$ but not working

**Comment by w0lfschild** [comment]
Can you upload a .zip of your crash logs and your current cDock settings?

`~/Library/Logs/DiagnosticReports` < Crash reports
`~/Library/Preferences/org.w0lf.cDock.plist` < cDock settings
`~/Library/Application Support/cDock/themes/*/*.plist` < Theme settings

**Comment by jeweljitu** [comment]
which ZIP file?



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*

**Comment by jeweljitu** [comment]
org.w0lf.cDock.plist not found
also not found ~/Library/Application Support/cDock/themes/*/*.plist < Theme
settings
I attached screenshot and crash report please check



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*


* <http://htechbd.com/>*

**Comment by w0lfschild** [comment]
I mean make a zip of those files.

`~` = `/Users/<your user name here>/`

**Comment by jeweljitu** [comment]
I send already please check. also, this is too bad to pay the app issue
later wait a long time to fix. also we have work. don't have time to wast
for this kind of work. please fix the app issue and update asap. or shall I
leave a 1 start 20 feedback with 20 ids?.



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*

**Comment by w0lfschild** [comment]
@jeweljitu  

1) Can you please try this build: [cDock v3.1.0](https://github.com/w0lfschild/app_updates/raw/master/test/cDock.3.1.0.zip)

2) If the issue persists can you re-send your crash logs and preferences zip to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.

You can reach me at: support@macenhance.com

**Comment by jeweljitu** [comment]
the still the same issue my friend. I can't use it. disappointed and wast
of money.



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*

**Comment by w0lfschild** [comment]
@jeweljitu 

Well if you'd like a refund just contact me support@macenhance.com with your order number or license number asking for a refund.

**Comment by jeweljitu** [comment]
refund not a solution. kindly check the software and solve the issue,
Catalina.



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*

**Comment by w0lfschild** [comment]
@jeweljitu    

1) Can you re-send your crash logs and preferences to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails so I've never received your logs.

2) Does the issue persist if you turn off icon reflections?

**Comment by w0lfschild** [comment]
@jeweljitu 

Try this new build : [cDock v3.1.1](https://github.com/w0lfschild/app_updates/raw/master/test/cDock.3.1.0.zip)

**Comment by jeweljitu** [comment]
can you recheck please coz download found 3.1.0, not 3.1.1

**Comment by etrahretep** [comment]
As for v3.1.0: still crashes the dock when opening/hovering downloads!

**Comment by jeweljitu** [comment]
:( yes still same issue.



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*

**Comment by etrahretep** [comment]
Also custom process indicators don't hide the original ones. (i see the black dot behind my custom white stripe)

**Comment by w0lfschild** [comment]
@jeweljitu 

Here's the correct link for : [cDock v3.1.1](https://github.com/w0lfschild/app_updates/raw/master/test/cDock.3.1.1.zip)

**Comment by jeweljitu** [comment]
Yeah now solved. Thank you very much!.



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*

**Comment by w0lfschild** [comment]
Sorry it took so long, had to reach out to another developer for some help finding the crash.

I've pushed the live version to v.3.1.2 with this fix and several others.

**Comment by jeweljitu** [comment]
cool. It's ok. I am very happy now. Thanks



 Have a nice day.

     Regards,

      Jewel.

* CEO = http://htechbd.com <http://htechbd.com>*

* <http://htechbd.com/>*
