### ISSUE TITLE
can't open my downloads folder without the dock crashing

### ISSUE THREAD

**Issue by quinton-ashley** [w0lfschild/cDock2#256]
I tried to reset the docks to the default and it keeps happening

**Comment by w0lfschild** [comment]
Can you upload a .zip of your crash logs and your current cDock settings?

`~/Library/Logs/DiagnosticReports` < Crash reports
`~/Library/Preferences/org.w0lf.cDock.plist` < cDock settings
`~/Library/Application Support/cDock/themes/*/*.plist` < Theme settings

**Comment by w0lfschild** [comment]
@quinton-ashley   

1) Can you please try this build: [cDock v3.1.0](https://github.com/w0lfschild/app_updates/raw/master/test/cDock.3.1.0.zip)

2) If the issue persists can you re-send your crash logs and preferences zip to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.

You can reach me at: support@macenhance.com
