### ISSUE TITLE
Black screen when clicking on Folders icon in dock occasionally

### ISSUE THREAD

**Issue by AJM-UK** [w0lfschild/cDock2#257]
Happens every few clicks.  I have a video but your upload won't allow me to attach it.  What do you advise?

**Comment by w0lfschild** [comment]
Can you upload a .zip of your crash logs and your current cDock settings?

`~/Library/Logs/DiagnosticReports` < Crash reports
`~/Library/Preferences/org.w0lf.cDock.plist` < cDock settings
`~/Library/Application Support/cDock/themes/*/*.plist` < Theme settings

**Comment by AJM-UK** [comment]
Crash logs, etc. attached as per your response.  Many thanks for your prompt intervention.  I have a screen recording video at 720p size 20Mb showing what happens if I can send that to you?

Best regards,

Alan Moore

**Comment by w0lfschild** [comment]
@AJM-UK 

Can you send them to my e-mail or attach them to this thread using the web interface. You can't attach files via GitHub reply emails.

You can reach me at: support@macenhance.com
