### ISSUE TITLE
Can't turn off dock transparency on 10.13.6

### ISSUE THREAD

**Issue by TheEvilKingBowser** [w0lfschild/cDock2#258]
I tried using cDock to bring back the 3D dock style on my early-2011 MacBook Pro running MacOS 10.13.6 (a.k.a High Sierra). However, trying to pick a background image only resulted in the dock being automatically made transparent. There are no selectable themes in the "Current Theme" tab, and trying to import a theme results in absolutely nothing happening. I really don't like the transparent dock, and resetting all dock settings still results in the dock automatically becoming transparent. I've tried checking and unchecking this option, and I've tried downloading and applying several old cDock themes designed for non-retina displays like mine, but NOTHING worked. Checking and unchecking the option briefly brought back the non-transparent dock, but it almost immediately turned transparent again. System Integrity Protection is off, by the way.

Please help! I absolutely despise the transparent dock that I'm currently stuck with.

**Comment by w0lfschild** [comment]
Not sure what to say, seems like you're having trouble figuring the settings out?

The themes folder is `~/Library/Application Support/cDock/themes`, so you can just manually add themes there if it's not working via the button in cDock.
