### ISSUE TITLE
Standard Indicator lights not covered by custom indicator lights

### ISSUE THREAD

**Issue by etrahretep** [w0lfschild/cDock2#260]
Standard Indicator lights not covered bij custom indicator lights

![Schermafbeelding 2020-03-18 om 09 18 33](https://user-images.githubusercontent.com/42773309/76939997-bde0e780-68f9-11ea-8539-15b213bea1fc.png)

 - OS: Macos 10.15.4 bèta (19E258a)
 - cDock Version 3.1.2

**Comment by jsteweii** [comment]
I have this also. A temp fix is to uncheck/recheck image indicator option.

**Comment by w0lfschild** [comment]
Should have a fix out for this soon.
