### ISSUE TITLE
hep with cdock

### ISSUE THREAD

**Issue by 1c3cr3amscr3am** [w0lfschild/cDock2#262]
Hi! I love your app; I've been using it for several years.
On this update, dock settings > show app indicator is randomly putting multiple dots instead of one next to an active icon.
Also, is there a way to have cdock start quietly when I start my computer (so it starts in the background, but the preferences pane and dock icon do not come up?
Thanks!

**Comment by w0lfschild** [comment]
Make sure the helper app and not the main app is in your login items in System Preferences.
