### ISSUE TITLE
license error

### ISSUE THREAD

**Issue by adriadri25** [w0lfschild/cDock2#263]
Hi,
I can't use my license anymore (a pop up with buy license appears every time).
![Screen Shot 2020-03-22 at 7 57 54 PM](https://user-images.githubusercontent.com/62297831/77257963-d8a7b900-6c77-11ea-9a19-98f6dbe0ed0a.png)
![Screen Shot 2020-03-22 at 7 57 54 PM](https://user-images.githubusercontent.com/62297831/77257975-e4937b00-6c77-11ea-9899-d9606511a3a7.png)

 Every time I start my PC I get an "Install Helper" popup window,
and my cdock is not working... I use cdock v.3.0.8  I tried the last version also but it is not working, please fix the errors!

Thank you!
Adrian H.

**Comment by w0lfschild** [comment]
If you haven't resolved this and are still interested in using the product it's best to email support at support@macenhance.com
