### ISSUE TITLE
cDock - Indikator light to big

### ISSUE THREAD

**Issue by McMacke** [w0lfschild/cDock2#264]
Hello!

I wish to be able to change the size of the indicator light with cDock.
(The point under the same program icon.)
The point in the dock is too big for me.

**Comment by w0lfschild** [comment]
This option exists already in the customize tab.

![Screen Shot 2020-07-03 at 1 02 51 AM](https://user-images.githubusercontent.com/1920148/86446530-ecc47300-bcc8-11ea-8784-15b9076ffc7b.png)
