### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by q64ceo** [w0lfschild/cDock2#265]
Back when 10.5 Leopard was released, the top menubar was transparent. Not everyone liked it. So a developer created a program called LeoColorBar. You would drop your images and it would add a color bar to the top of the pic to disable the transparency of the Mac menubar.

The program also had one feature: a box that said "Fix my dock, too". It would then make the 3d dock 2d again.

I would like for you to mimic the main function of LeoColorBar. LeoColorBar is 32bit and was abandoned over a decade ago. It broke sometime around 10.9, so even if I had say 10.14 installed I would not be able to use it.

**Comment by w0lfschild** [comment]
Unfortunately not something I'm able to do.
