### ISSUE TITLE
Dock Indicator Badges Suppressed

### ISSUE THREAD

**Issue by defrilitus** [w0lfschild/cDock2#267]
On macOS 14.6, when the screen and cDock restart after sleep, cDock suppresses the "new" red badges on all apps (e.g., Mail, Messages, Whatsapp).
That obviously means that one has to reopen all such apps manually, one by one, to check new notifications.

**Comment by w0lfschild** [comment]
That's just the default behavior when the Dock restarts. Not sure why it's crashing when you wake from sleep though.

Do you have crash logs for the dock located here: `~/Library/Logs/DiagnosticReports/Dock_.....crash`

**Comment by defrilitus** [comment]
I think you missed the fact that
      we already had this conversation:
      
      Thanks for your quick reply. Much appreciated.
        I actually just figured out the issue an hour ago. The cause was
        actually not cDock itself; I was using some AppleScripts to
        pause certain applications when the screen slept and I realised
        today that, for some reason, cDock was being paused—or shut
        down, I'm not sure which—as an unintended result. (The same
        thing was happening to Hyperdock, but I only noticed that
        today.)
        So I got rid of the scripts and everything back to normal. And,
        as you imagined, the problem wasn't related to cDock at all.
        Apologies for the misunderstanding on my part and thanks again
        for your answer.
         
        > To: Alessandro Fontana <alessandro@fontana.com>
        > From: Macenhance Support <support@macenhance.com>
        > Date: Tue 28 Apr 2020 23:08:11 +0000
        > Subject: Re: "New" Badges Suppressed
        That’s actually just how the Dock works, badges are only drawn
        when an app tells them to be drawn. If the Dock restarts there
        won’t be any notification badges shown until the app either gets
        a new notification or is relaunched.
        Attached is an example video demonstrating the same issue,
        without cDock enabled.
        You can send your crash logs and I’ll check if they’re maybe
        related to cDock? Crashes are located here:
        /Library/Logs/DiagnosticReports
        > On Apr 22, 2020, at 11:07 AM, Alessandro Fontana
        <alessandro@fontana.com> wrote:
        > 
        > On macOS 14.6, when the screen and cDock restart after
        sleep, the latest version of cDock suppresses the "new" red
        badges on all apps (e.g., Mail, Messages, Whatsapp).
        > That obviously means that one has to reopen all such apps
        manually, one by one, to check for new notifications.
        > I have used cDock since it first came out and I am positive
        that this didn't happen in previous versions.
        > Could you therefore send me a link to a previous version
        that works on Mojave and that doesn't exhibit this behaviour?
        > 
        > Thanks in advance,
        > 
        > Alessandro
      
      Thanks anyway 😉
      
       
    
    
      
        
          
        
        
          To: W0lfschild/cdock2
          <cDock2@noreply.github.com>
          CC: Defrilitus <alessandro@fontana.com>, Author
          <author@noreply.github.com>
