### ISSUE TITLE
[Feature] Ability to hide trash

### ISSUE THREAD

**Issue by jonteamere** [w0lfschild/cDock2#27]
I empty my trash trash like a maniac secondary to my obsessive personality. It's a dangerous game. I'd rather just hide that mess in case I end up needing something. Thoughts or ideas on how I can do this immediately?

**Comment by w0lfschild** [comment]
With System Integrity Protection disabled you can edit the DockMenus plist to allow the Trash and Finder to be removed. See here: https://discussions.apple.com/thread/6638249?start=0&tstart=0

It's something I could look into but I'm not sure about.

**Comment by w0lfschild** [comment]
I've come up with a way to do this on the fly without any Dock interaction required. It will be included in a future version.
