### ISSUE TITLE
lic has been utilized

### ISSUE THREAD

**Issue by itlinux** [w0lfschild/cDock2#270]
I just got a new Mac, this seems silly to have this tight not to be able to install or have to ask every time, if I reinstall etc..Thanks

**Comment by w0lfschild** [comment]
What's the email you used to get the license?

**Comment by itlinux** [comment]
remo@mattei.org <mailto:remo@mattei.org> or remo@italy1.com <mailto:remo@italy1.com> it may have been rm@rm.ht <mailto:rm@rm.ht> so (Remo Mattei) is the name

**Comment by w0lfschild** [comment]
Alright reset it for you.
