### ISSUE TITLE
cDock 3.1.2 stopped working.

### ISSUE THREAD

**Issue by zorba33** [w0lfschild/cDock2#272]
Hi.
About 3 weeks ago I installed cDock on my new Mac mini. It worked until this morning. When I restarted the mini, the dock appeared without my theme background colour. I opened cDock and discovered that the dock was in fact frozen to applying my theme or any other theme or any individual change I tried to apply. Restoring from backup did not restore any functionality. Deleting the com.apple.dock.plist and/or org.wOlf.cDock.plist and org.wOlf.cDock-GUI.plist didn't help either.
I have a 2018 Mac mini with two volumes, one Catalina 10.15.4 and the second Mojave 10.14.6. cDock 3.1.2 failed on the Mojave volume.
What's wrong? How do I fix it? Please help.
Best regards, Chris Tomaziu

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/282
