### ISSUE TITLE
Reflection of finder icon showing when it's hidden

### ISSUE THREAD

**Issue by HanneMaes** [w0lfschild/cDock2#274]
Found a small bug.
The reflection of the finder icon is visible, but I've hidden it.

<img width="362" alt="finder reflection" src="https://user-images.githubusercontent.com/19576877/84478735-14a85400-ac92-11ea-994b-92c3818541ff.png">

**Comment by w0lfschild** [comment]
Finally got a fix for leaving straggler reflections. Will be included in the next version of cDock.

**Comment by HanneMaes** [comment]
Cool, thanks!
