### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by BeeJaythedj** [w0lfschild/cDock2#277]
Hi w0lfschild, Hope your well, Just wonder if there will be an update for cDock 3. I have installed BIG SUR beta, The dock causes the screen to flash on and off. LOVE THE APP. I've had it a few years now. Great job. 
<img width="314" alt="Screen Shot 2020-07-05 at 11 41 42 am" src="https://user-images.githubusercontent.com/67848011/86524069-f7dbf680-beb4-11ea-97bc-90f88bec6de8.png">

**Comment by w0lfschild** [comment]
It will get updated sometime before the public release yes.

![Screen Shot 2020-06-29 at 1 18 26 PM](https://user-images.githubusercontent.com/1920148/86524332-2236a100-be2e-11ea-9200-fcdce3f5337c.png)

Until then go delete `/Library/Application Support/MacEnhance/Plugins/cDock.bundle`

**Comment by BeeJaythedj** [comment]
I have deleted cDock.bundle. a few times. it keeps reappearing.

**Comment by w0lfschild** [comment]
Don't run cDock after you delete it or it will be automatically re-added. 

You could also remove the cDock Helper from your login items and log out and back in.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/276
