### ISSUE TITLE
Dock keeps crashing an restarting when I hover over it

### ISSUE THREAD

**Issue by Antonios-P** [w0lfschild/cDock2#279]
I don't know what to say for this one, I have an unusable dock. When I hover over it, the whole screen turns black and the dock restarts. This happens constantly if I hover over the dock and stops when I don't use it. This happened after Applying the OS X 10.5 theme and doesn't fix when changing it or restoring the theme to default. All help is appreciated. I am running Mac OS X Catalina 10.15.5.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/cDock2/issues/282
