### ISSUE TITLE
cDock didn't upgrade the helper plugin when I installed the most recent version. How do I do it manually?

### ISSUE THREAD

**Issue by TheEvilKingBowser** [w0lfschild/cDock2#280]
So a while back, I purchased and installed cDock onto my early 2011 MacBook Pro running Mac OS X 10.13. However, themes didn't work properly for some reason, so I deleted it but forgot to uninstall the old version of the plugin. Recently, I used dosdude1's patch to upgrade my MacBook to Mac OS X 10.14, and then decided to install cDock again because I noticed it'd been updated recently and I was hoping the new version might've fixed some bugs. However, the new version didn't upgrade the already-installed plugin when I launched it, causing the Dock to crash and refuse to open until I disabled the cDock helper plugin. I deleted the old helper plugin, thinking that cDock might try to reinstall it, but that didn't work. How do I manually install the helper plugin?

**Comment by w0lfschild** [comment]
Try downgrading to version 3.0.9

https://github.com/w0lfschild/cDock2/issues/282
