### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by matteoinnocenti301** [w0lfschild/cDock2#281]
hi I bought the cdock application but opening it and setting everything doesn't change my dock****

**Comment by w0lfschild** [comment]
Do you have SIP off? 
What version of macOS?
What version of cDock?
Is the helper running?

**Comment by matteoinnocenti301** [comment]
yes I disabled the SIP
 I have the mac version is 10.15.6 while the cdock v1.0.4

**Comment by w0lfschild** [comment]
Update cDock
