### ISSUE TITLE
Can SIP be re-enabled after installation?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [w0lfschild/cDock2#29]
I thought SIP had to be disabled for cDock2 to run, because the instructions make no mention of enabling it again. I've been running my Mac with SIP disabled for months, since installing cDock, and I thought it was still disabled. But I just tried to install another app which also requires that SIP be disabled, and it couldn't install because it says SIP is **enabled**.

It's likely that SIP was re-enabled a few days ago when I reinstalled the OS, but I never noticed since cDock still works and my chosen theme is functional. I've now read online that some apps only require SIP be disabled during installation.

If it's only necessary for SIP to be disabled during install, then the instructions need to say that SIP should be re-enabled after installation.

**Comment by w0lfschild** [comment]
This is correct SIP only needs to be disabled for SIMBL to be installed.

From what I can tell some updates may move SIMBL to a quarantine folder which would require SIP to be re-disabled to allow another installation. I have only had this happen once though in a beta update.

**Comment by Ajaymamtora** [comment]
This doesn't seem to be the case anymore on 12.2 beta + MBP with an M1 Pro

**Comment by w0lfschild** [comment]
@Ajaymamtora 

Notice this issue is 5 years old and closed. This hasn't been the case for a long time.

SIP has to remain disabled to run cDock or any other app that uses code injection into a protected app.
