### ISSUE TITLE
Need help adding cDock Helper as login item

### ISSUE THREAD

**Issue by Hanly-Wijaya** [w0lfschild/cDock2#309]
Whenever I login, the cDock Helper doesn't open.

It should open every time I login.

Desktop: Big Sur 11.0.1
iMac 2015

I need help adding the cDock Helper to my login items.

**Comment by w0lfschild** [comment]
- Navigate to the cDock app in Finder
- Right click and select `Show Package Contents`
- Navigate to `../Contents/Library/LoginItems/cDock Helper.app`
- Open `System Preferences > Users & Groups > Login Items`
- Drag the `cDock Helper` into the list

**Comment by Hanly-Wijaya** [comment]
Fixed, thanks!
