### ISSUE TITLE
Manual entering on plist not working.

### ISSUE THREAD

**Issue by dorrek** [w0lfschild/cDock2#31]
So i tried to create my own theme using the codes under plist but they don't seem to work at all, also before you used to be able to slant the icons on the dock either more left/right is that gone?

**Comment by w0lfschild** [comment]
I would need more info about what you're doing. Plist editing works fine, although it's unnecessary as the app has controls for basically all the variables that you would edit in the plist.

There was never an option to slant icons but there was an option to adjust the dock background height and width. Is that what you're asking about?

**Comment by dorrek** [comment]
See I realized if you switch from the current them you're working on to another and vise verse the plist edits work. 

Yes that's what I meant, are those options gone?

**Comment by w0lfschild** [comment]
Currently there is no way to manually shift the dock background layer.
