### ISSUE TITLE
CDock 2 don't work on my  Mac osx High sierra

### ISSUE THREAD

**Issue by Horizonthevent** [w0lfschild/cDock2#315]
I had to reinstall everything by replacing the hard disk, the technician also updated my computer to high sierra and all the animation effects on the icons when I swiped over no longer work, it gives me an error warning that I cannot resolve!
![Schermata 2021-06-21 alle 16 57 13](https://user-images.githubusercontent.com/86246590/122783710-17c91d80-d2b2-11eb-8b49-6fa378679b6a.png)
![Schermata 2021-06-21 alle 16 57 13](https://user-images.githubusercontent.com/86246590/122783793-2d3e4780-d2b2-11eb-9f77-a7a9e6c6310f.png)

**Comment by w0lfschild** [comment]
Did you turn off System Integrity Protection?
