### ISSUE TITLE
BigSur.

### ISSUE THREAD

**Issue by doriansgithub** [w0lfschild/cDock2#316]
how do I activate and deactivate cDoc. It's interfering with BigSur.

**Comment by w0lfschild** [comment]
Currently if you want to stop it from loading delete this bundle and then restart the Dock

`/Library/Application Support/MacEnhance/Plugins/cDock.bundle`

**Comment by doriansgithub** [comment]
Are you guys trying to fix it or it’s over?

**Comment by w0lfschild** [comment]
Fix what? The app works on Big Sur and if you want a version for Monterey you can get it in our Discord.

**Comment by doriansgithub** [comment]
It doesn’t work for me. The menu bar turns off and on, on a loop.

**Comment by w0lfschild** [comment]
Hmm well sounds like it's crashing. Are you using the latest version? You could also try the beta on our Discord.

https://discord.gg/EBvWEMGx

**Comment by doriansgithub** [comment]
Ok, will do. Thanks.
