### ISSUE TITLE
All sliders are decreasing when changing themes.

### ISSUE THREAD

**Issue by Wandmalfarbe** [w0lfschild/cDock2#32]
Steps to reproduce:
- Switch to theme X and set the slider for _Corner radius_ to 0.8
- Switch to another theme
- Switch to theme X
- The corner radius is now at 0.7 and when I repeat the steps it decreases to about 0.5

The problem occurs on all sliders.

**Comment by w0lfschild** [comment]
Interesting I'll look into this.

**Comment by w0lfschild** [comment]
Think it should be fixed in the next release, it had to do with going from int to float.

**Comment by w0lfschild** [comment]
Should be fixed as of 1.0.3
