### ISSUE TITLE
0.11.3 not working properly on 10.12 beta

### ISSUE THREAD

**Issue by lenn5** [w0lfschild/cDock2#33]
Theme 10.4 not working properly. Vertical line on dock overlaps icons among other problems.

**Comment by lenn5** [comment]
Is the 0.11.3 version of cDock that a few web sites have a legitimate version? I don't see this version of the developers web page.

**Comment by w0lfschild** [comment]
Yes 0.11.3 is legitimate but I pulled it because I need to do more research about SIMBL running on 10.12. As well as make some new UI telling users they need to disable System Integrity Protection for certain updates.

**Comment by jaflonpink** [comment]
Hi w0lfchild 
Any update yet for 10.12 beta?
Regards

**Comment by w0lfschild** [comment]
Sorry I got wrapped up in trying to add in some new stuff and got sidetracked so I went back to the last push here and I just pushed out 0.11.4 which is only a tiny change to get things working on 10.12

Hopefully I didn't break anything else.

🐺

**Comment by lenn5** [comment]
Where can we find 0.11.4? this site's latest version is only 0.10.3.
thx

**Comment by w0lfschild** [comment]
Oops well looks like 0.11.3 had a higher build number than what I put out.

The source of all updates is here: https://github.com/w0lfschild/app_updates/tree/master/cDock

**Comment by lenn5** [comment]
I just tried to install 0.11.4 and when I clicked the install button for SIMBL nothing happened. I have rootless disabled so not sure why it's not installing. Am using the latest Sierra seed as of Aug. 27.

**Comment by w0lfschild** [comment]
I put out 0.12.1 hopefully that should fix things up.
