### ISSUE TITLE
[Bug?] Have to re-enter admin pw after every reboot

### ISSUE THREAD

**Issue by JayBrown** [w0lfschild/cDock2#34]
After updating to the latest version I have to re-enter my admin password after every reboot/login for the cDock helper, sometimes also for the SIMBL Helper. This wasn't necessary in previous versions. (??)

**Comment by w0lfschild** [comment]
Install 0.11.2 or disable System Integrity Protection. It's an update for SIMBL, but there will be another one with the next update so I'd just use 0.11.2 for now.

**Comment by JayBrown** [comment]
I don't think it has anything to do with SIP, because that has been disabled on my Mac since El Capitan day 1. So I assume that cDock (or easySIMBL) is the reason.

**Comment by JayBrown** [comment]
Do you mean v0.10.2? At any rate, I can neither find 0.11.2 nor 0.10.2, and mySIMBL gives the cDock version number as 0.38.8.

**Comment by w0lfschild** [comment]
https://github.com/w0lfschild/app_updates/blob/master/cDock/cDock_0.11.2.zip

**Comment by Wandmalfarbe** [comment]
I just wanted to say that installing 0.11.2 fixed the problem for me.

**Comment by manaretalkhale1** [comment]
http://al-nadaa.com/%D8%A7%D8%AE%D8%A8%D8%A7%D8%B1-%D8%A7%D9%84%D8%AA%D9%86%D8%B8%D9%8A%D9%81-%D9%88%D8%A7%D9%84%D9%86%D8%B8%D8%A7%D9%81%D9%87/%D8%B4%D8%B1%D9%83%D8%A9-%D8%AA%D9%86%D8%B8%D9%8A%D9%81-%D8%AE%D8%B2%D8%A7%D9%86%D8%A7%D8%AA-%D8%A8%D8%A7%D9%84%D8%AF%D9%85%D8%A7%D9%85-757/
