### ISSUE TITLE
cdock: different look on computers

### ISSUE THREAD

**Issue by hansluyendijk** [w0lfschild/cDock2#37]
Hi there,
I'm working in Macos Sierra 10.7 and wonder how it is possible that the 3d-dock is visible on my MacBook pro, but is still two-dimensional on my iMac? I'm using the latest version of cdock (posted yesterday...)
Anyone?

**Comment by w0lfschild** [comment]
Could be a permissions issue or something of the sort. What exactly isn't working on the iMac. I'd need some more information.

**Comment by hansluyendijk** [comment]
I hope these screenshots are helpful
thnx! Top=iMac, bottom=MacBook, both are installed the same way (see screenshot cdock)
<img width="644" alt="schermafbeelding 2016-09-17 om 09 13 51" src="https://cloud.githubusercontent.com/assets/21307648/18606691/4ce90b3e-7cb7-11e6-9860-f1775d7b2b7d.png">

<img width="1149" alt="imac" src="https://cloud.githubusercontent.com/assets/21307648/18606672/baac576c-7cb6-11e6-9c01-afc1cd81d21a.png">
<img width="852" alt="macbook pro" src="https://cloud.githubusercontent.com/assets/21307648/18606673/bb0a3e68-7cb6-11e6-9bc7-e30dc4559454.png">

**Comment by w0lfschild** [comment]
Looks like on the iMac it is not working at all. Probably some install issue. I'd need more information to understand why.

**Comment by hansluyendijk** [comment]
I copied all cdock files exactly as they were installed on my MacBook Pro, (preferences, Application Support stuff etc.), but it didn't change a thing whatsoever...

**Comment by hansluyendijk** [comment]
Problem solved! It turned out that the cdock.bundle plugin in SIMBL was an old version; I replaced it and now everything works great! Thnx, though for your support!
