### ISSUE TITLE
[cDock 0.12.1] Printer Que app not Auto-Quitting

### ISSUE THREAD

**Issue by herbs** [w0lfschild/cDock2#38]
I'm not sure if this is some interaction from cDock or SIMBL but suddenly my Printer Que app and even the Archive Utility app no longer auto-quit when they are finished.

Sorry if this is irrelevant but I don't know how to get in touch with the owner directly.

**Comment by herbs** [comment]
Of course the title should contain 0.12.1 rather than 0.12.0.

**Comment by w0lfschild** [comment]
I'll look into this. Probably has to do with SIMBL.

**Comment by herbs** [comment]
Maybe these might be a help. I have two diagnostic reports about SIMBLAgent:


[SIMBLAgentCrashes.zip](https://github.com/w0lfschild/cDock2/files/465456/SIMBLAgentCrashes.zip)

**Comment by w0lfschild** [comment]
My guess is that I actually just need to block injection into those apps by default.

The crashing is another issue that needs to be figured out.

**Comment by herbs** [comment]
> On Sep 10, 2016, at 1:23 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> My guess is that I actually just need to block injection into those apps by default.
> 
> The crashing is another issue that needs to be figured out.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Howdy,

Hmmm... I was trying to isolate the problem a bit better and for a short period simply tried to remove SIMBL.osax. The crashes may have been from that attempt so don't pay too much attention to them.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by herbs** [comment]
By `those apps' I assume you mean all apps owned by Apple. If I click on Terminal in the dock (I have it there permanently) it starts up but doesn't open a window. If I unzip a file Archive Utility opens but doesn't auto-quit (like it used to.

**Comment by herbs** [comment]
I just updated to Sierra on one system and this problem persists there. Hope it can be corrected and the `injection' isn't a permanent thing.

**Comment by herbs** [comment]
The problem persists with cDock 0.12.2. See also my report on 0.12.2 not activating at login.

**Comment by w0lfschild** [comment]
Yeah I would need to add the printer queue and archive utility to the simbl blacklist to stop this from happening.

**Comment by herbs** [comment]
I assume that would mean going through the `csrutil routine'  again once SIMBL gets fixed. Please let us know. Thanks for being responsive on this.

**Comment by w0lfschild** [comment]
No recently I moved to my version of SIMBL which will only require SIP to be disabled if the SIMBL.osax bundle needs to be updated which ideally should be never.

**Comment by herbs** [comment]
> On Oct 15, 2016, at 4:02 PM, Wolfgang Baird <notifications@github.com> wrote:
> 
> No recently I moved to my version of SIMBL which will only require SIP to be disabled if the SIMBL.osax bundle needs to be updated which ideally should be never.

That's great to know! Looking forward to an eventual update to fix this problem.

Good Luck,

Herb Schulz
(herbs at wideopenwest dot com)

**Comment by herbs** [comment]
I noticed another anomaly. I keep Terminal in the Dock. When I clicked on the Dock Terminal icon it used to open and also open a Terminal window. Clicking now opens the Terminal app but no Window opens; I have to click the icon a second time for the Window to open. I don't know if this is related to other problems with OS supplied applications.

**Comment by herbs** [comment]
Just used the latest mySIMBL (thank you!) to add Archive Utility and my printer apps and, of course, the problem has gone away. I believe the printer apps really just pass some information to PrinterProxy. I wonder if adding PrinterProxy to the blacklist would fix all printers.
