### ISSUE TITLE
Will mySIMBL be used in future releases?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [w0lfschild/cDock2#39]
The cDock2 page makes no mention of using mySIMBL (which w0lfschild is now developing).
I'm wondering why cDock2 doesn't install mySIMBL since SIMBL hasn't been updated in 5½ years and EasySIMBL _reportedly_ doesn't work properly on OS X 10.9+.

I don't know which version has been included in the cDock updates, but it's been working fine for me on OS X 10.11.6.

> mySIMBL is a successor to the application EasySIMBL. This application uses my own version of SIMBL since both EasySIMBL and the original SIMBL no longer work properly on macOS 10.9 and above due to changes made by Apple. Since both projects seem to have been abandoned or left unsupported I have created mySIMBL. It is designed to make finding, updating and installing SIMBL plugins easier than ever.

https://github.com/w0lfschild/mySIMBL

**Comment by w0lfschild** [comment]
Actually as of 0.12.1 I'm using [mySIMBL](https://github.com/w0lfschild/mySIMBL).

The code for my version of SIMBL can be found here: https://github.com/w0lfschild/SIMBLFramework

**Comment by GitTheHellOutaHere** [comment]
OK, thanks.

The last version listed in the outdated version history is SIMBL 0.9.10.

**Comment by w0lfschild** [comment]
Where is that listed? I've got so many small projects I've lost track of a lot of stuff.

**Comment by GitTheHellOutaHere** [comment]
https://github.com/w0lfschild/cDock2/blob/master/release/versionInfo.txt


> cDock.app		: 0.10.3
> cDock.bundle		: 0.11.2
> SIMBL.osax		: 0.9.10
> cDockHelper.app		: 1.0
> Build Date 		: Feb / 05 / 2016

**Comment by w0lfschild** [comment]
That's only there for legacy update reasons and doesn't have anything to do with the current release. Before I used sparkle I used something I made myself and that file is for that.
