### ISSUE TITLE
Icon reflections not working properly on version 11.3/12.1

### ISSUE THREAD

**Issue by ghost** [w0lfschild/cDock2#40]
Tried using older versions (pre 11) in which icon reflections work as intended. However theming in general doesn't work too well (its not working at all except for correct icon reflections - didn't try anything else) with older versions on 10.12!
Anyway, 12.1 _does_ draw icon reflections, but only on icons of currently active apps which is slightly annoying. (refer to picture below)

Reproduction:
Tried on clean install as well - same behaviour
Seems to happen from version 11 (at least, not sure about 10)
The bug also occurred on 10.10.5; currently running 10.12 (16A320)
would use older versions but as mentioned above, they're not working too well

![bildschirmfoto 2016-09-10 um 15 51 20](https://cloud.githubusercontent.com/assets/22117469/18410991/753f73fa-776e-11e6-95dd-cbd475edc74c.png)

**Comment by w0lfschild** [comment]
That's the way icon reflections originally worked so I changed it to match that.

The old cDock functionality may return as an option in the future.
