### ISSUE TITLE
OSAscript or SIMBLhelper on 0.12.1

### ISSUE THREAD

**Issue by R-S-T** [w0lfschild/cDock2#41]
Either OSAscript or SIMBLhelper are popping up on every computer startup, asking to install something. After typing in my admin password OSAscript gives no message, SIMBLhelper gives an error that it was not installed properly.
But cdock seems to work correctly.

This was introduced in version 0.12.1 Didn't happen before.
Any thoughts?

regards
Ralf

**Comment by R-S-T** [comment]
btw, all this is on Yosemite 10.10.5

**Comment by w0lfschild** [comment]
SIMBL update so SIP needs to be disabled.
