### ISSUE TITLE
Is cDock cause of Console messages?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [w0lfschild/cDock2#42]
Do these continual Console messages have anything to do with cDock?
I'm guessing no, but wanted to ask since dock is mentioned.

9/15/16 9:31:28.262 PM sandboxd[130]: ([5482]) com.apple.WebKit(5482) deny mach-lookup com.apple.dock.fullscreen

9/15/16 9:31:50.267 PM sandboxd[130]: ([5482]) com.apple.WebKit(5482) deny mach-lookup com.apple.dock.fullscreen

9/15/16 9:32:02.271 PM sandboxd[130]: ([5482]) com.apple.WebKit(5482) deny mach-lookup com.apple.dock.fullscreen

9/15/16 9:32:14.276 PM sandboxd[130]: ([5482]) com.apple.WebKit(5482) deny mach-lookup com.apple.dock.fullscreen

9/15/16 9:32:26.282 PM sandboxd[130]: ([5482]) com.apple.WebKit(5482) deny mach-lookup com.apple.dock.fullscreen

**Comment by w0lfschild** [comment]
I'm not sure. I don't get these warnings.
