### ISSUE TITLE
Dock in left is fullscreen

### ISSUE THREAD

**Issue by unluisco** [w0lfschild/cDock2#43]
![monosnap 2016-09-29 10-57-41](https://cloud.githubusercontent.com/assets/6332263/18961780/cec0fd30-8633-11e6-97c1-f6d9c36b50aa.png)

I hope that this can be repaired

**Comment by JayBrown** [comment]
Which OS? Sierra? I'm still on 10.11.6, and everything's fine here with the Dock on the left. (Using transparent setting.)

**Comment by unluisco** [comment]
Yes, Sierra, in The Capitan all was fine

**Comment by grkka** [comment]
@unluisco Nobody has said that cDock supports Sierra.

Description
cDock - Unleash your Dock

Small program to customize your dock on OS X 10.9 Mavericks, 10.10 Yosemite, and 10.11 El Capitan. There are several dock styles included and users can also create their own custom docks.

**Comment by unluisco** [comment]
@grkka 
> I hope that this can be repaired

**Comment by liam4** [comment]
But if cDock is to survive, it's going to need to support Sierra (if possible) at some point! Which means that bug reports for cDock on Sierra *are* helpful, right?

**Comment by JayBrown** [comment]
Of course they are. :)

**Comment by tralalafugl** [comment]
Please take a look at the issue when positioned on the Right Hand side of the Display also.

Thank you.

**Comment by tralalafugl** [comment]
@grkka cDock in its latest revision does support macOS Sierra - go fetch v. 0.12.1

**Comment by flakpanda** [comment]
I got this as well. Notice that the fullscreen button only changes the width of the dock regardless of position. So while on the bottom, it appears to work correctly. I don't know how easy of a fix this is, but I hope this helps.

**Comment by w0lfschild** [comment]
Okay. Next update will fix this issue.

**Comment by adamw79** [comment]
+1ing to chime in that I just did a clean install of macOS Sierra, a clean install of cDock, reboot into recovery, terminal, enter csrutil disable, reboot into desktop, terminal, enter csrutil status, get: "System Integrity Protection status: disabled."

At initial application startup, cDock wants me to enter my password. After I enter it, I get the error message for SIMBL. I can manipulate some of the dock themes, but when I move it to the left and try to do full screen I get the same result as the first post here by unluisco, with the vertical dock full width covering the screen horizontally. 

I've come to rely on cDock and have donated before, but I just sent you $10.00....waiting for a fix! Let me know if I can assist with troubleshooting in any way.

**Comment by w0lfschild** [comment]
Fixed.

**Comment by adamw79** [comment]
Downloaded the update via the app and can confirm I have a proper fullscreen menu bar again. Thanks!

**Comment by adamw79** [comment]
Not sure if this is connected to this issue or if it deserves a new issue... after updating to this fix, when I restart, cDock doesn't theme the dock. I have to manually start cDock and click restart dock to get the theme to apply. Thanks.
