### ISSUE TITLE
After uninstall, every time unlock mac, this will show up

### ISSUE THREAD

**Issue by cmal** [w0lfschild/cDock2#45]
Insecure update error!
For security reasons, you need to sign your updates with a DSA key. See Sparkle's documentation for more information.
![d129ff69-6422-4f41-bb64-3b592470924f](https://cloud.githubusercontent.com/assets/1773318/19181069/12a9e51a-8c9d-11e6-9f4e-ae222958902c.png)

**Comment by cmal** [comment]
![9aa413f2-c7f1-4b8a-8318-30f03317840d](https://cloud.githubusercontent.com/assets/1773318/19181112/666f441a-8c9d-11e6-9b6b-39758dc43c6f.png)

**Comment by w0lfschild** [comment]
Wait so this is happening after you uninstalled cDock?

**Comment by cmal** [comment]
Yeah. So I reinstalls cDock2. and this window does not show up now. How can I have a clean uninstall? thanks!

**Comment by w0lfschild** [comment]
I'm not sure why this was happening in the first place because I do have the updates signed. I'm guessing it was some sort of cache issue or something with your computer.

**Comment by cmal** [comment]
I'm using a new mbpr. I know nothing about signing updates with DSA keys. Before the first time I installed cDock2, I installed a former (7.1.1) version of cDock and then uninstalled it. And is this something rate to the disabling of System Integrity Protection? because I reenabled it after installing cDock2.

**Comment by cmal** [comment]
And when i reboot mac, this shows up now:
SIMBL install failed!
Something went wrong, probably System Integrity Protection.

**Comment by w0lfschild** [comment]
Sounds like System Integrity Protection needs to be disabled so cDock can update the SIMBL.osax file.
