### ISSUE TITLE
cDock 0.12.2 not applying at login

### ISSUE THREAD

**Issue by herbs** [w0lfschild/cDock2#46]
Howdy,

Just installed cDock 0.12.2 and re-booted. Even though it is set to startup at login I had to open cDock and restart the Dock. Note: cDockHelper is on the login list. I'm using Sierra. It seems to be working properly under El Capitan.

Good Luck,
Herb Schulz

**Comment by stiffyfoto** [comment]
me too, 0.12.2 doesn't load at login under Sierra.

**Comment by w0lfschild** [comment]
I'm looking into this.

**Comment by darkcrow25** [comment]
Same Issue here, I have to reinstall cdock to make it work again but every time I turn on the mac same issue.

Regards

**Comment by w0lfschild** [comment]
Didn't have anything to do with Sierra, should be fixed now.

**Comment by herbs** [comment]
cDock 0.12.4 fixed this problem for me.

Thanks for the quick work.
