### ISSUE TITLE
cDock old custom themes are still there even after uninstall

### ISSUE THREAD

**Issue by BTTF-DeLorean** [w0lfschild/cDock2#47]
I used the 10.8 theme, but now it doesn't work. It stopped working ever since I tired to install an old version of cDock (yes I know that's weird to do, I was just experimenting ). All other themes work fine, I tried to uninstall cDock but when I download it again, it still doesn't work and I still see old custom themes in the cDock themes menu that don't exist anymore in cDock/Contents/Resources/themes. How can I remove cDock completely and start over? Thanks

10.8 theme worked fine before...
<img width="1280" alt="screen shot 2016-10-06 at 3 08 18 pm" src="https://cloud.githubusercontent.com/assets/22828787/19374016/6d7a8064-917d-11e6-9a4d-90eaae9372ff.png">

But even when I uninstalled it and installed it again, I still see all the old custom themes(which means that there is still some files from the old cDock somewhere.) I want to uninstall cDock completely and start fresh.
<img width="1280" alt="screen shot 2016-10-13 at 7 40 57 pm" src="https://cloud.githubusercontent.com/assets/22828787/19373978/04ebd7b4-917d-11e6-9ea4-239a2e8b8af5.png">

**Comment by w0lfschild** [comment]
Delete ```~/Library/Application Support/cDock/themes``` then re-open cDock.

**Comment by BTTF-DeLorean** [comment]
It works! Thank you so much!
