### ISSUE TITLE
io. page

### ISSUE THREAD

**Issue by usego1** [w0lfschild/cDock2#48]
on io page it give V10.3 TO DOWNLOAD!
http://w0lfschild.github.io/app_cDock.html  !!! ATTN!

My 12.4 works fine on Sierra but sometimes on startup i does not start, but i serch the app and start then the theme is apply ! Very great program !! Thanks, Vielen Dank !

**Comment by w0lfschild** [comment]
I will update this at some point soon. Thanks for the heads up.

**Comment by w0lfschild** [comment]
I've updated the page to the most recent version.
