### ISSUE TITLE
cDock forces discrete GPU to be used on retina MBP

### ISSUE THREAD

**Issue by corporate-gadfly** [w0lfschild/cDock2#49]
Once cDock is opened, the GPU changes to discrete (instead of integrated). This can be bad for battery life.

**Comment by w0lfschild** [comment]
Like the actual application or having a theme active? I don't have a mac with integrated and discrete graphics to test with.

**Comment by corporate-gadfly** [comment]
Just the app when I open `cDock.app`  (not the themes). Is there something that I can help test with?

**Comment by corporate-gadfly** [comment]
[This](https://developer.apple.com/library/content/qa/qa1734/_index.html) suggest setting the value to `true` in `Info.plist`.

**Comment by corporate-gadfly** [comment]
Added this near the bottom of `/Applications/cDock.app/Contents/Info.plist`
```xml
    <key>NSSupportsAutomaticGraphicsSwitching</key>
    <true/>
```
and so far so good. Discrete CPU is not triggered.

**Comment by w0lfschild** [comment]
Alrighty then, I can add this in a future build.
