### ISSUE TITLE
Login items bug

### ISSUE THREAD

**Issue by dkfiresky** [w0lfschild/cDock2#5]
Why do i have to fill in my password for 4 times each time when I log in?

![screenshot 2015-10-21 20 47 46](https://cloud.githubusercontent.com/assets/2175645/10645203/376882e4-7835-11e5-909c-19d8de5166d6.png)

> You can view the logs of the agent at "$HOME"/Library/Application\ Support/cDock/logs/agent.log

agent.log:
```
/Applications/cDock 2.app/Contents/Resources/cDock-Installer.app
/Applications/cDock 2.app/Contents/Resources/updates/wUpdater.app/Contents/MacOS/wUpdater
/Applications/cDock 2.app
/Applications/cDock 2.app/Contents/Resources
SIMBL check #1
SIMBL check #2
SIMBL check #3
SIMBL check #4
SIMBL check #5
restart count is now : 1
Starting crash loop monitoring
Stopping crash loop monitoring
restart count is now : 1
Starting crash loop monitoring
Stopping crash loop monitoring
```

Ref: [#47](https://github.com/w0lfschild/cDock/issues/47)

**Comment by w0lfschild** [comment]
Because it's trying to install SIMBL and SIP is preventing it from doing so and the maximum times it asks before giving up is 4.

Open terminal and see what you get when you enter:
```bash
locSIMBL=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" /System/Library/ScriptingAdditions/SIMBL.osax/Contents/Info.plist)
curSIMBL=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" /Applications/cDock\ 2.app/Contents/Resources/cDock-Installer.app/Contents/Resources/SIMBL.osax/Contents/Info.plist)
echo -e "Loc: $locSIMBL\nCur: $curSIMBL"
```

Should be:
```
Loc: 0.9.10
Cur: 0.9.10
```

**Comment by dkfiresky** [comment]
@w0lfschild I have SIMBL already installed, cDock should not try to install it again if it already exists.
Your script returned error:
```sh
Print: Entry, "CFBundleVersion", Does Not Exist
-e Loc: 0.9.9
Cur: File Doesn't Exist, Will Create: /Applications/cDock 2.app/Contents/Resources/cDock-Installer.app/Contents/Resources/SIMBL.osax/Contents/Info.plist
```

**Comment by w0lfschild** [comment]
It should be trying to install it again because it's not the most up to date version.

**Comment by dkfiresky** [comment]
It should not, because SIMBL is used not only by cDock. SIMBL may be used by other software. If your app updates SIMBL this could break other software.

I think it should ask (or warn) before performing any action rather than updating automatically.

**Comment by dkfiresky** [comment]
I think there was already an option to enable/disable SIMBL auto-updates.
Also, there is `Automatically install updates` checkbox in `Preferences` that can be also used for SIMBL updates.

**Comment by w0lfschild** [comment]
Hmm maybe but I'm not likely gonna change the way this works. I don't really plan on changing the SIMBL version again unless it was absolutely necessary.

**Comment by dkfiresky** [comment]
This issue is not reproducible anymore, I think this might get fixed with re-installing fresh new cDock with SIP disabled.
