### ISSUE TITLE
[Question] - Modified Dock binary instead of SIMBL

### ISSUE THREAD

**Issue by mk2soldier** [w0lfschild/cDock2#50]
Hello guys, first of all I would like to thank you (w0lfschild) for the wonderful piece of software, very useful (for me at least).

I have a question though: is there a way (with or without the aid of cDock) to produce a modified Dock executable to use in a more "persistent" fashion (id est: **without using SIMBL** to patch the Dock binary on the fly)?

I'm currently aware of the DockMod application that (for what I've heard on various forums on the Internet) replaces the original binary with a modified one, **I would like to replicate that functionality** without the associated limitations of DockMod: the "DockMod Trial" label under every Dock item highlight and the scarce quantity of applicable themes/colors.

System Integrity Protection won't be a problem for me since I'll leave it disabled.

Sorry if it is unrelated to cDock but I couldn't find a better place to write to..

Thank you again!

**Comment by w0lfschild** [comment]
All I can say is that I won't be making this.
