### ISSUE TITLE
cDock2 - Theme changes not recognized

### ISSUE THREAD

**Issue by jeGit** [w0lfschild/cDock2#52]
Hello,
I have upgraded to cDock2 and now I notice that any theme changes will not be recognized. E.g., I had previously 'Transparent' theme and selecting this again in cDock2 and click on 'Restart Dock' does not change anything.
OSX Yosemite 10.10.5
MBP15' Early2012
Tia,
Jens

**Comment by jeGit** [comment]
Any logfile I can provide?

**Comment by w0lfschild** [comment]
Um I don't really have a lot of logging set up at the moment. You might try deleting ```~/Library/Application Support/cDock/themes``` then reopening cDock. Also make sure SIMBLAgent is running in Activity monitor.

**Comment by yuvista** [comment]
I have same problem here .
just try : 
` cd /Library/Application\ Support/SIMBL`
romoved all the file here , and restart cDock2 .
It`s work for me.
