### ISSUE TITLE
[Feature] cDock theme that looks like Mavericks dock

### ISSUE THREAD

**Issue by BTTF-DeLorean** [w0lfschild/cDock2#53]
This is not an issue, but could you make a theme for cDock that looks exactly like the dock in Mavericks? The current 3d themes are not like that. Thanks.

**Comment by w0lfschild** [comment]
I'm not an artist so unfortunately no I wont be making this, but if someone else does I'll gladly include it by default.

**Comment by Wandmalfarbe** [comment]
I made some themes a while ago <https://github.com/Wandmalfarbe/cDock-Themes>. Unfortunately there's no Mavericks theme at the moment.
@w0lfschild maybe you could include them in cDock?

**Comment by dmklsv** [comment]
I'm working on it. Unfortunately, in the Mavericks is no image files directly in the system draws the dock. It is generated from the code. Very hard to get a sense of the Mavericks dock because the code cDock differently renders reflections and casts no shadow. But I'm close. Soon I will share with you.

**Comment by dmklsv** [comment]
![cdockmav](https://cloud.githubusercontent.com/assets/25923097/23300094/1beca1ec-fa95-11e6-97d3-e4adab696218.png)
![cdockmav2](https://cloud.githubusercontent.com/assets/25923097/23300191/8a4608cc-fa95-11e6-9e4b-0d3acfec12ac.png)
![cdockmav3](https://cloud.githubusercontent.com/assets/25923097/23300250/c70331ea-fa95-11e6-8ee6-736404c3970b.png)
What do you think is good enough?
Anyway, thanks to the developers, cDock helped me move on from Mavericks

**Comment by YHVHvx** [comment]
@dmklsv there is any progress for mavericks look ?
