### ISSUE TITLE
The application "The Unarchiver" doesn't work properly when cDock is running

### ISSUE THREAD

**Issue by adamwinn** [w0lfschild/cDock2#54]
When cDock is running, The Unarchiver just opens its preferences dialog box and won't run.  See https://github.com/jsdf/theunarchiver/issues/583.  It appears to be an issue with SIMBL.

**Comment by adamwinn** [comment]
It looks like it was because of the SIMBL app jp.cvz.colorfulsidebar.  I was only able to see this app after I installed mySIMBL.

**Comment by adamwinn** [comment]
Thank you for the colorfulSidebar9 plugin!!

**Comment by w0lfschild** [comment]
Glad you got things sorted.
