### ISSUE TITLE
No icon reflections on inactive apps

### ISSUE THREAD

**Issue by BTTF-DeLorean** [w0lfschild/cDock2#55]
Even though I checked Show icon reflections, it only shows the reflections on apps that are running, once I close them, the reflections disappear.
<img width="106" alt="screen shot 2016-12-02 at 4 42 37 pm" src="https://cloud.githubusercontent.com/assets/22828787/20855117/9e6babbe-b8ae-11e6-8241-b5d536c1339c.png">
As you can see, only mail has reflections because it's open.

**Comment by w0lfschild** [comment]
That is currently the intended functionality. That is how the reflections used to work when the dock implementation by Apple had reflections.

**Comment by plsrspnd** [comment]
Actually, it used to show reflections of all the apps on the dock. 
![maxresdefault](https://cloud.githubusercontent.com/assets/6070091/21597449/1c6c1c7e-d132-11e6-8d09-070e1292472b.jpeg)

**Comment by Skyyblaze** [comment]
I'm a new cDock user and would also like to optionally show reflections on each icon, would that be possible in a future update?
