### ISSUE TITLE
cDock theming not working

### ISSUE THREAD

**Issue by ryantrip** [w0lfschild/cDock2#56]
Any change I make to the theming tab has no affect on my dock.

MacBook Pro 13" 2016 TB
macOS Sierra 12.2
System Integrity Check - Disabled
cDock 0.12.4

**Comment by w0lfschild** [comment]
What if you open terminal and run?

```bash
osascript -e "tell application \"Dock\" to inject SIMBL"
```

My guess is either one of two things is happening

1) SIMBL is not installed/loading
2) cDock themes folder is not set up somehow

**Comment by JayBrown** [comment]
The same thing happened to me after updating to mySIMBL 0.4.2 (first 0.4.1). Safari stopped injecting SafariStand via SIMBL. The osascript, changed for Safari, worked for me. At first I suspected it to be a SafariStand bug, but it seems that the mySIMBL update did something. (Tried rebooting, but that didn't help.)

**Comment by JayBrown** [comment]
PS: After quitting and relaunching Safari, injection was disabled again, i.e. SafariStand is not working. So there seems to be something wrong with the latest SIMBL/mySIMBL.

**Comment by JayBrown** [comment]
Fixed with v0.4.3. Thank you!

**Comment by ryantrip** [comment]
The themes folder must have been the issue, because the new update fixed it for me.
