### ISSUE TITLE
Unable to change settings & no themes are shown

### ISSUE THREAD

**Issue by wallace-aph** [w0lfschild/cDock2#59]
Hello, I'm unable to make any changes to my dock without it going transparent, and no themes exist in the dropdown. I've tried cDock on a clean MySIMBL (as well as easySIMBL).

This is what the menu looks like when "Disabled Theming" is pressed (dock does restart)

![image](https://i.imgur.com/TFcbTdr.png)

Once changes are made, dock looks like this no matter what I configure:

![image](https://i.imgur.com/NfX3wXC.png)

I've tried multiple fixes, and have restarted many times. Nothing's worked thus far.

Resources/theme folder in app IS populated, SIMBL daemon is running, SIP is disabled, and cDock2 is in the "enabled" plugins folder

Using latest version of cDock, MySIMBL 0.4.3, and El Capitan

**Comment by w0lfschild** [comment]
You need to select a theme from the dropdown. If none are show try creating a new one from the menubar.

Something might be wrong with the folder `~/Library/Application Support/cDock/themes` on your computer, check to make sure it exists. It should be automatically created but it is required for cDock to theme, cDock reads it's theming settings from there.

**Comment by wallace-aph** [comment]
Thanks, the themes existed in the app's directory (Contents/Resources/themes) but not in ~/Library/Application Support/cDock/themes. Copied them over and now it's working, not sure why they weren't already there.
