### ISSUE TITLE
Cannot pick image for application indicator

### ISSUE THREAD

**Issue by criticalmaze** [w0lfschild/cDock2#60]
Title says it all, I select the Image application indicator box and I can see nothing on selecting my own image.

![screen shot 2017-01-17 at 18 39 12](https://cloud.githubusercontent.com/assets/25182805/22034457/441ea6fc-dce4-11e6-9baf-5ca0d1fd9db1.png)

**Comment by w0lfschild** [comment]
Right now you have to manually add the images to the theme folder yourself. An image picker will be added in the next update.
