### ISSUE TITLE
Not able to show the icon for the apps that are open

### ISSUE THREAD

**Issue by dnecklesportfolio** [w0lfschild/cDock2#61]
I'm not able to show only the icons that are open... I can make the dock transparent.
What am I doing right. I am using total finder so i don't know if that has something to do with it

**Comment by dnecklesportfolio** [comment]
The options in the theming screen work well, but not the options on the dock screen

**Comment by w0lfschild** [comment]
Probably an issue with your file ~/Library/Preferences/com.apple.dock.plist

This likely has nothing to do with using Total Finder. Is cDock crashing or is nothing saving?

**Comment by derimagia** [comment]
Having issue similar to this. Preferences Icon won't load. If I reload the dock it works fine but this happens for other apps as well.

<img src="https://i.imgur.com/1j4UsU8.png"/>

**Comment by w0lfschild** [comment]
Could be an issue with your Dock cache. cDock doesn't do anything with application icons that would result in that.

```
sudo find /private/var/folders/ -name com.apple.dock.iconcache -exec rm {} \;
sudo find /private/var/folders/ -name com.apple.iconservices -exec rm -rf {} \;
sudo mv /Library/Caches/com.apple.iconservices.store com.apple.ic
```
