### ISSUE TITLE
cDock App blocks standard hotkeys

### ISSUE THREAD

**Issue by derimagia** [w0lfschild/cDock2#63]
Cmd + w doesn't work in the app to close it,

cmd + a, cmd + v, cmd + c don't work in colorpickers when open from cDock2 which is strange too. They work normally elsewhere. (See https://twitter.com/bjango/status/840508271299506176 where I originally thought it was the colorpicker)

Mac 10.12.3
cDock 2 0.12.4

**Comment by w0lfschild** [comment]
Thanks for the feedback.
