### ISSUE TITLE
Theming suddenly lost; other utils suddenly went poof, too. 

### ISSUE THREAD

**Issue by brianaweeks1** [w0lfschild/cDock2#64]
Theming suddenly lost when starting up computer this morning. MBP 2013 integrated graphics, 10.12.3. Also, Karabiner, iStat Menus, did not work. cDock's "dock" pane works, but theming does not, and generic frosted dock appears. Did in-place reinstall of full 10.12.3 from fresh download. Removed clock's ~/lib/application support folder, and every preference file I could see in ~/prefs and ~prefs/by host that had 'dock' or 'cdock' in it. Disabled SIP. Used SIMBL uninstaller and uninstalled SIMBL. Then reinstalled cDock, SIMBL, with SIP still off. Same issue; no theming, but 'dock' pane in cDock works. Karbiner and iStat Menus worked after the OS reinstall, but had to reinstall each of them, too. Why suddenly these 3 utils dropped functioning, IDK. SIMBL and cDock processes shown running in Activity Monitor. Tried bringing over all such files from my safety clone drive over, still no dice. I notice this problem also exists in the other user account on this computer. Still works fine on my other Mac 10.12.3. Ideas what to fix?

**Comment by brianaweeks1** [comment]
Additional note to the above. Theming pane in cDock shows the theming preferences I had customized down to a T; clearly not the defaults for the Transparent theme my cDock choices are based on.

**Comment by w0lfschild** [comment]
Not sure, probably SIMBL not installing properly for some reason. You could try using mySIMBL.
