### ISSUE TITLE
Theme no longer applies at startup, MacOS 10.12.3

### ISSUE THREAD

**Issue by sprokolopolis** [w0lfschild/cDock2#67]
cDock works fine when I manually apply a theme in the app with the "Apply" button, but when I reboot the theme does not apply on startup anymore. The theme settings are preserved but it just needs to be applied manually or sometimes I need to use the "Restart Dock" button. I have noticed that the Console app reports a crash on both cDockHelper and SIMBL Agent anytime the computer starts up. I have attached the crash logs.

I have tried uninstalling with App Cleaner (to get any other stray related files) and reinstalling, but still have the issue. I tried uninstalling SIMBL and reinstalling it.

Running cDock 0.12.4 (4039), which seems to be the latest.
macOS 10.12.13

Crash Logs:

[cDockHelper_2017-03-20-034935_MacBook-Pro.crash.txt](https://github.com/w0lfschild/cDock2/files/857203/cDockHelper_2017-03-20-034935_MacBook-Pro.crash.txt)
[SIMBL Agent_2017-03-20-034939_MacBook-Pro.crash.txt](https://github.com/w0lfschild/cDock2/files/857204/SIMBL.Agent_2017-03-20-034939_MacBook-Pro.crash.txt)

**Comment by w0lfschild** [comment]
Still having this issue on the latest version?

Make sure the helper app is running on startup.
