### ISSUE TITLE
Remove dock 4px gap margin on hiding

### ISSUE THREAD

**Issue by ellipticaldoor** [w0lfschild/cDock2#69]
When you maximize a window with the dock hidden it leaves a 4px margin gap. Can this app remove it? I can't find it on the options.

**Comment by w0lfschild** [comment]
Is this normal functionality of the Dock or a bug with cDock or a feature you want for cDock? 

It's certainly something I could look into.

**Comment by ellipticaldoor** [comment]
Awesome! How is this going?

**Comment by w0lfschild** [comment]
Looking back at this I don't see this behavior at least on the latest version of macOS.
