### ISSUE TITLE
Folders on Top

### ISSUE THREAD

**Issue by slvrscoobie** [w0lfschild/cDock2#7]
installed cDock hoping i could get my folders on top to work again now that Xtrafinder doesnt work correctly in 10.11. 
But unlike the preview images, I dont see any option for that in cDock 2
Am I missing something?

**Comment by dkfiresky** [comment]
You can check the cDock [releases](https://github.com/w0lfschild/cDock/releases) page for information on changes.

Latest version changes:
> App : cDock 2
> Version : 0.9.7
> Build : 1205
> Status : Public
> Date : Oct / 03 / 2015
>
> - New -
> 
> 🆕 UI rewritten in Objective C
> 🆕 Vibrant window option on Yosemite and above
> 🆕 SIMBL information window
> 🆕 Rootless information windows
> 🆕 Theme changes applied without dock restarts
> 🆕 Edit every theme variable in-app
> 🆕 Show themes folder
> 🆕 Name themes when creating them
> 🆕 3D docks improvements
> 🆕 10.9 dock appearance is more in line with 10.10+ docks 
> 🆕 Separator layer can be colored
> 🆕 Separator layer can be full height of dock
> 🆕 Separator layer is displayed in 3D docks
> 🆕 Icon reflections bounce
> 🆕 Bug fixes and performance improvements
> 
> - Removed -
> 
> ❌ Menubar application (No longer useful)
> ❌ Dock plist backups
> ❌ Reset icon cache option
> ❌ Finder Folders on top
> ❌ Finder Colored sidebar (Use XtraFinder)

**Comment by w0lfschild** [comment]
Yeah this was removed. You could install an older version of cDock to use this feature if you need it, you'd need to have System Integrity Protection off for it to be able to work though.
