### ISSUE TITLE
3D Dock image isn't Retina

### ISSUE THREAD

**Issue by MikeBeas** [w0lfschild/cDock2#70]
Super small, low-priority issue here. The image that's used when the "Use image for Dock background" option is enabled on the default theme isn't designed for Retina Macs and has a lot of aliasing on the edges. The same is true for the 3D version of the separator image. (Semi-related: the separator image could probably be a little lower on the dock to be more centered vertically; just another small observation).

This isn't a really huge deal but I thought I'd mention it just in case someone out there wants to contribute a better image. I don't have one or I would.

**Comment by w0lfschild** [comment]
Good point. If I ever get some retina themes I'll add them.

**Comment by Wandmalfarbe** [comment]
I just released all my themes with high resolution retina images. You can download them here: https://github.com/Wandmalfarbe/cDock-Themes
