### ISSUE TITLE
High Sierra

### ISSUE THREAD

**Issue by usego1** [w0lfschild/cDock2#73]
Will the GREAT App Cdock Work on high Sierra ?

thanks for your Work ! Love it evry da not to have the grey dock !

**Comment by w0lfschild** [comment]
Yes it does. 👍

**Comment by herbs** [comment]
Howdy,

I assume you have to do the usual temporary disable of SIP to re-install SIMBL.

**Comment by usego1** [comment]
Yes true ! dsiable SIP by Boot to Reovery Com+ R  tehn Csrutil Disable  restart and start cdock ! then reinstall SIMBL  then it works whit high Sierra ! Version is 12.4 dont now if a newer is there.
