### ISSUE TITLE
Dock and background app clash

### ISSUE THREAD

**Issue by aspiringcaprofessional** [w0lfschild/cDock2#75]
Hi I've got somewhat of a peculiar bug.

When I click the application folder in the Dock and use my keyboard (either arrow marks / letters to select an application or move around, I notice that the app in the background (any app like chrome or excel or anything) types or performs the same action as the keyboard strokes

Attaching a screenshot which may help understanding the issue.

If you notice in the screenshot below
1. I opened the applications folder
2. I typed "safari" so that I could select the app
3. Safari is selected in the applications BUT "safari" is also typed in the app behind. Which shouldnt be happening. Right ?

<img width="1280" alt="screen shot 2017-08-21 at 1 21 18 am" src="https://user-images.githubusercontent.com/31001882/29497940-5b87ce66-860f-11e7-9a6b-b4aafa368adc.png">

Please help ! Annoying at times

**Comment by w0lfschild** [comment]
I can't replicate this. My guess would be that it's an un-related issue. Probably a restart or log out and back in would fix this.

**Comment by aspiringcaprofessional** [comment]
Tried restarting it. No luck :(

**Comment by w0lfschild** [comment]
Okay so 2 things:

1. I did get this to happen without anything loaded into the dock on 10.13 (so it's not a cDock issue)
2. After testing a few apps (Safari, Chrome, TextEdit, Sublime Text, Messages) it only happens with Chrome so likely it's an issue with Chrome not releasing focus.

**Comment by aspiringcaprofessional** [comment]
Thank you for your reply on this, Wolfgang Baird.

I hope its sorted out soon. Not sure if this is a chrome issue or MacOS
issue since it did happen with other apps like Finder too.

I realised it happens the first time when you open the stack on the dock.
After that it somehow doesnt repeat instantly. After a while the focus is
again in 2 places ie. the app open and the grid.


*Vipul Mehta*

**Comment by aspiringcaprofessional** [comment]
Again rechecking on this.

Not sure if this helps but I have total finder installed as well. Do you
think it can be a total finder issue ?


*Vipul Mehta*

**Comment by w0lfschild** [comment]
This is an issue with most likely Chrome and/or macos. Not something related to cDock.

**Comment by ptkrisada** [comment]
Dear all,

I found one dock from Mountain Lion and I love this dock theme so much.
Please someone tell me, where can I get this dock theme?
Thanks in advance,

[image: Inline image 1]

-- 
Best Regards,

​Gua Chung Lim
