### ISSUE TITLE
iOS 11 iPad style dock

### ISSUE THREAD

**Issue by acondiff** [w0lfschild/cDock2#76]
Would it be possible to move the dock up a few pixels and round the bottom two corners to resemble the dock introduced in the ipad in iOS 11?

![image](https://user-images.githubusercontent.com/806104/30256624-c62c1cfa-9671-11e7-9015-8e445d2d7049.png)

**Comment by ThePotatoKing55** [comment]
[Whipped up something like it, but I'm not sure how to add the blur effect other than a blurred desktop image as the dock. Not the best, but gets the general look.](https://github.com/w0lfschild/cDock2/files/1363387/iPad.Style.zip)

**Comment by acondiff** [comment]
Is it moved up or is it flush with the bottom of the screen?

**Comment by ThePotatoKing55** [comment]
Moved up 8px.

**Comment by jakeround** [comment]
Would also love an iOS 11 styled Dock
