### ISSUE TITLE
"dock dark mode" option not working on high sierra

### ISSUE THREAD

**Issue by jlrpc1** [w0lfschild/cDock2#77]
Dock won't change mode if you change it inside the options of cDock (2nd option inside "Theming"). Dock keeps the same theme as system. This means the dock itself AND its menus.
I can change the dock color itself, but not the menus. They stay the same as the system theme.
This is important if you want your system on light but your dock (and its menus) on dark.

**Comment by w0lfschild** [comment]
Thanks for the heads up.

**Comment by aekiameh** [comment]
Yeah, same here. Was thinking I was missing something, but the menus remain light, while they used to be able to show up dark, which I preferred. I don't want the menu bar to show dark as well, so if this could be fixed somewhere again, that would be wonderful!

**Comment by w0lfschild** [comment]
Not sure how to pull this off in such a simple way as it used to be but if I figure it out I'll add the feature back. For now you can just manually make the Dock use a Dark Background, Labels, Folders, App Switcher, etc...

**Comment by w0lfschild** [comment]
Okay I've found a method to force the Dock menus dark, not sure about light though. I'll probably add it the next release regardless.
