### ISSUE TITLE
3D is not working in High Sierra

### ISSUE THREAD

**Issue by swattw** [w0lfschild/cDock2#78]
After I re-install High Sierra in my MBA, I also install the new version of cDock.
But unfortunately that cDock is work everything well but 3D dock.
I hate the new version Dock in Sierra.
But before I reinstall MacOS it works great in 3D.
I 've tried every option in the preference, but doesn't work.
How can I get the 3D dock back?
![2017-10-17 9 12 10](https://user-images.githubusercontent.com/19372998/31642353-163b0292-b2b0-11e7-8e28-2f156c314a33.png)

**Comment by w0lfschild** [comment]
Maybe try deleting your theme and reloading?

![screen shot 2017-12-01 at 11 53 13 pm](https://user-images.githubusercontent.com/1920148/33513209-d33ef770-d6f2-11e7-9afa-0f6ff4c090cd.png)

**Comment by w0lfschild** [comment]
Was this ever resolved? I'm closing this for now.
