### ISSUE TITLE
[Feature] Continuity theming

### ISSUE THREAD

**Issue by nyreed** [w0lfschild/cDock2#8]
With this option set, the "mini-dock" which pops up when something is open on iPhone has the background image, but doesn't seem to have the flared edges like the main dock.

Actually, the edges of the mini-dock are vertical, even when the edges of background.png arent.

**Comment by w0lfschild** [comment]
I don't have a computer that is new enough to test continuity on.

**Comment by w0lfschild** [comment]
I now have a Mac that supports Continuity, what would this look like?

An extension of the existing theme, or something else?

**Comment by recuerom** [comment]
<img width="415" alt="screenshot of safari" src="https://user-images.githubusercontent.com/15388514/37955129-729809e6-31f3-11e8-8c88-510a6190a31f.png">

It would be nice if the continuity dock was a continuation of the existing theme.
