### ISSUE TITLE
cDock installed in mySIMBL but I don't have cDock in Applications

### ISSUE THREAD

**Issue by ggregoire** [w0lfschild/cDock2#80]
OS: El Capitan
SIP: disabled

As you can see, cDock is installed:

![screen shot 2017-11-22 at 12 38 36](https://user-images.githubusercontent.com/591804/33144346-58f0823a-cf82-11e7-9351-5ba00b1852ef.png)

But I don't have the app in Applications.

Bininventory works properly.

**Comment by ggregoire** [comment]
I updated my OS to High Sierra and I still don't see cDock. I tried with spotlight but it doesn't see it neither.

**Comment by ggregoire** [comment]
I uninstalled cDock in mySIMBL and reinstalled cDock manually (from the website). Now I have cDock in Applications.

Could be an issue with mySIMBL or the version of cDock shipped with mySIMBL.

I let the issue opened, you can close if the issue is not directly related to this repo.

**Comment by w0lfschild** [comment]
Totally logical. Right now mySIMBL just installs plugins and not any helper apps, that's something I want to implement in the future.
