### ISSUE TITLE
Where, oh where have the updates gone?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [w0lfschild/cDock2#84]
Why is the latest release posted here v0.10.3 from Feb. 5, 2016?
Why have this GitHub project posted here at all if it's not going to be updated?

Even the [main cDock site](https://w0lfschild.github.io/app_cDock) is virtually useless.

It doesn't provide any insight as to what the latest version is. There's only a download button and a button that links to this site, where someone can download a 2-year-old version that probably won't work right. Then they'll probably get frustrated and either uninstall it or end up asking for help here, because for some reason the [Issues page](https://github.com/w0lfschild/cDock2/issues) _is_ still being updated.

And since there's no release notes posted on the main site either, users have no idea what has changed from version to version.

I thought I had the latest release because I hadn't received an update notice in ages.
But after checking MacUpdate today I found that I've been running the previous version for 14.5 months.

Do I _need_ the latest version? **WHO KNOWS?!**
There's no way to tell from the cDock site or here.

But thanks to MacUpdate it seems I might - release notes _are_ posted there.
And they say v0.12.4 contains bug fixes and resolves a codesign issue.

So the dev. spent his time fixing problems in the software, then didn't bother mentioning it on his own site and hasn't told anyone on GH about a new version in over two years.

But the Download button on the cDock site _does_ download the latest version. Go figure.

Evidently, the first rule about cDock is you don't talk about cDock.

**Comment by w0lfschild** [comment]
All quite valid points.

There is a compatibility reason why the latest release on GitHub is old. I used to use a updater I made myself that pulled from the releases page and if the download didn't have that updater in the app bundle then updating from an old version would fail.

I'll check back and see if maybe I can find an old build of the project and just add the updater in and publish it to the releases page.

I don't have much web development skills, or lots of free time these days, so yeah the cDock website is pretty bare-bones.

Thanks for the feedback.

**Comment by GitTheHellOutaHere** [comment]
Have you tried getting someone else to take on the project?
Hate to see it die, Crapple's dock is godawful.

The only theme I like is 3D Clean, but that's a big improvement.

Interesting: I just opened cDock to find the name of the theme, and a Little Snitch window appeared warning about the app being unsigned.

> cDockHelper wants to connect to github.com on TCP port 443 (https)

> The process has no code signature. The executable can be maliciously modified without being detected.

**Comment by w0lfschild** [comment]
@GitTheHellOutaHere 

No, I haven't tried to have anyone else take on the project, although I'm welcome to contributions.

I think the cDockHelper might not have been signed in older versions, it is for sure signed in cDock 3.

I've updated the main site to use https:// and added a changelog, screenshots, and a description.

This issues pages was my main report tracking area, now that's the built in feedback with DevMate since it's much more user friendly for an average user.

I'm still considering adding the old updater to the current release of cDock.

For now I'm going to close this.
