### ISSUE TITLE
Can't enter license

### ISSUE THREAD

**Issue by JayBrown** [w0lfschild/cDock2#88]
I've just received my Paddle license code for cDock3, but I can't enter the license code. The app launches fine, everything works, but there is no "Enter License" button, and when I click on "Purchase", nothing happens. (OS X 10.11.6)

**Comment by w0lfschild** [comment]
What happens if you restart cDock? If it's not showing something like this then it's already activated.

<img width="849" alt="screen shot 2018-03-18 at 5 38 38 pm" src="https://user-images.githubusercontent.com/1920148/37573287-6c114f5a-2ad3-11e8-8abc-98cd71366161.png">

**Comment by JayBrown** [comment]
That window popped up only at the first launch, but it was completely blank. Now it doesn't pop up at all anymore. It can't possibly be activated since I've never entered the license code. Weird. I'll have a look at my Little Snitch rules, but I'm pretty sure I allowed every connection.

**Comment by JayBrown** [comment]
Yup, it's not activated yet, because the hide-donate & -ad buttons are still greyed out. Same with v1.0.2. So it means that the trial period will at some point run out, unless I somehow manage to enter the license key. Of course, I can script an auto-delete of the padl file, but that's not really how it's supposed to be. ;)

![grab1](https://i.imgur.com/vC44FNB.jpg)

By the way, mySIMBL tells me that I still have v2.0.1 installed in /Library, even though I removed the old version, and v3 installed a new file in there.

![grab2](https://i.imgur.com/GhpcGgZ.jpg)

**Comment by JayBrown** [comment]
Just now cDock presented the 14-days trial period prompt again, and I was finally able to enter the license code and activate the app. Phew. :)

**Comment by w0lfschild** [comment]
I've also added a button to enter a license specifically / de-activate the current license in 1.1.0

**Comment by JayBrown** [comment]
Just happened again on a fresh install on Mojave (SIP still enabled). Doesn't accept my Paddle license.

![snap](https://i.imgur.com/vrOyebg.jpg)
