### ISSUE TITLE
arabarab

### ISSUE THREAD

**Issue by arabarab** [w0lfschild/cDock2#9]
Hello,
Can you please explain how to create new themes in cDock2.I've tried adding curve files to a duplicate of the £D dock theme but all I get is a transparent dock.I would ideally like to make the 3D dock shelf larger -as it was in Snow Leopard and move the icons further up the dock as they were in Snow Leopard.
Regards.

**Comment by w0lfschild** [comment]
The 3D dock is just background.png in the themes folder. As for adjusting the icon positioning cDock can not do that.

**Comment by arabarab** [comment]
Hello again,
I fully understand that the 3D dock is a png file,but my problem is when I replace it with a different png this does not appear as a 3D dock-the dock is completely absent,only icons are left.How does one change the 3D dock?.
Regards.

**Comment by w0lfschild** [comment]
I dunno you might not be using a .png or you might just have the dock settings not set up properly for your theme. Themes only use the background picture if set to do so.
