### ISSUE TITLE
Help Wanted : Themes

### ISSUE THREAD

**Issue by w0lfschild** [w0lfschild/cDock2#90]
I'm looking for some assistance with a theme that resembles the 3D dock which was available from about 10.8 - 10.9

![img](https://i.ytimg.com/vi/brurTnYdp6E/maxresdefault.jpg)

I'm willing to pay something like $20 for a high quality theme made to resemble that classic look to add to cDock.

Also if you have already made a theme and would like it added to cDock feel free to post it here, I'd like to expand the stock offerings available in the app.

**Comment by w0lfschild** [comment]
Related issues: https://github.com/w0lfschild/cDock2/issues/53 https://github.com/w0lfschild/cDock2/issues/70  https://github.com/w0lfschild/cDock2/issues/76 https://github.com/w0lfschild/cDock2/issues/79

**Comment by recuerom** [comment]
Ditto for me, that is THE dock !!

**Comment by ExactProbability** [comment]
I have made a dock theme that is similar? to the one in the screenshot. Can be seen here:
<img width="1727" alt="newfancy" src="https://user-images.githubusercontent.com/25787371/37769878-cb357b30-2dd2-11e8-8347-9b0e751310ff.png">

I have also made a few other Dock themes for cDock 3 that you may include if you want to. same background but 4 colors.
https://github.com/ExactProbability/Sharas-cDock

I also have them uploaded to https://www.deviantart.com/allannyholm/ - except for the first Dock image in my comment here.

**Comment by w0lfschild** [comment]
@ExactProbability Wow that actually looks really nice. I've contacted you via email about buying the 10.8/10.9 theme.

I'd also probably be interested in adding the other themes as they look pretty polished as well.

Thanks.

**Comment by recuerom** [comment]
I agree with @dockdude 's comments, there should be an option in Cdock to reposition icons if you are using a 3D dock image (ie move them back). Also would be nice to slide control the alpha of the reflections independently (as you can with the 3D image) to get a custom look. Love this product, my ultimate aim is to get back to the Dock at the start of the post.

**Comment by recuerom** [comment]
I agree with @dockdude 's observations. I would like to see options in Cdock to a) reposition icons (back) when using 3D images and b) change the image alpha of the reflections independently to suit taste. My ultimate aim is to get back to the top image, I think we are getting there. Great product !

**Comment by ExactProbability** [comment]
While making new Docks for cDock3 I've come to realise the importance of having icons moved back 50 percent from where they are now. Even just 40 percent. I would have to remake the indicators for some of my recent (unpublished) dock themes but I bet it will be worth it.

Thanks for the kind words here in this thread. I know that I haven't made the complete Mountain Lion Dock as seen in the original image - Sadly I'm unaware of a way to really but that type of blue on top an  image, unless a transparent image with a gaussian blur does the trick.  I recently made a dock theme that used some background blur from within Sketch - however cDock didn't take that appearance. It could make for some cool dock looks down the line if cDock would take the exact image and use it.

I'll have to experiment some more with cDock themes..

**Comment by recuerom** [comment]
@exactprobability. Thank you for uploading and sharing your work here. Some nice new themes to try out. If Cdock can improve the reflection intensity I will be very happy. Unfortunately Apple ‘s flat theme and round icons don’t do Cdock and your artwork justice.

**Comment by jsteweii** [comment]
I made a Mavericks -esqe dock for you. Size is a bit too small, but that's intentional so as to not get too much dock behind the icons.

![screen shot 2019-01-28 at 16 00 44](https://user-images.githubusercontent.com/30780358/51844746-4aa39d00-2316-11e9-9e32-daa98d0069ee.png)

Another one will be coming up soon too. And by the way, I agree with @recuerom. If the features he mentions could be implemented, so much more accurate and also nicer themes could be made:-).

best regards,

-jsteweii

**Comment by recuerom** [comment]
Nice work @jsteweii , you hit the nail in the head. In the current execution of Cdock the best you can do is find a dock png that is small so that the perspective shows like before. If you are sharing the theme is there a link ?

Thanks,

Mario

**Comment by jsteweii** [comment]
Hey Mario, take a look at my Deviant Art page:

https://www.deviantart.com/jsteweii/art/Mavericks-783845879

-jsteweii

**Comment by recuerom** [comment]
Thank you @jsteweii , looks great. Truly designed for what Cdock can product. Love the proportions.

**Comment by jsteweii** [comment]
Thank you, I'm glad you like it:-).
