### ISSUE TITLE
GUI bug: indicator lights too far left

### ISSUE THREAD

**Issue by JayBrown** [w0lfschild/cDock2#92]
indicator lights are too far left; they're kind split in half
(obviously for setups with the Dock on the left side, but it's the same on the right)

![grab1](https://i.imgur.com/JjS2ZKm.jpg)

PS: edit > Finder/Trash problem solved; missed the respective settings

**Comment by w0lfschild** [comment]
Hmm I'll fix this in the next release. Not sure why I had them shifted over like that.

**Comment by w0lfschild** [comment]
Should be fixed in 1.0.3
