### ISSUE TITLE
Not Compatible with TotalSpace 2.6.24

### ISSUE THREAD

**Issue by recuerom** [w0lfschild/cDock2#93]
Been using Cdock 12.4 and TotalSpace 2.6.XX (binaryage.com) for at least 18 months without issues. Moved to Cdock 1.01 (and 1.02) and 2.6.22 and 2.6.24 and the TS program no longer switches spaces (other than by using track pad gesture). TS does a dock restart every time it is restarted so the programs have some 'dock link'. This is under 10.13.3

At this point can TS (24 or 26) switch spaces thru the trackpad gesture but all other switch methods (menu, hot corner,) go nowhere.

In a 10.13.6 beta 5 with 2.6.24 and Cdock old 12.4 all is good.

**Comment by w0lfschild** [comment]
Will fix in the next release.

**Comment by recuerom** [comment]
Looks OK with Cdock 1.03. Many thanks.
