### ISSUE TITLE
Finder an Trash icon missing after Uninstall

### ISSUE THREAD

**Issue by eptik** [w0lfschild/cDock2#94]
When I uninstalled Cdock, my trash and finder icons disappeared, the dock became invisible leaving just the icons and the separator is now black

I then updated MacOs to the latest version but the dock is still invisible and no trash nor finder icon
![image](https://user-images.githubusercontent.com/37584377/37657684-fdaeb262-2c4b-11e8-88ff-937d40faa28d.png)

**Comment by w0lfschild** [comment]
Open Terminal and run:

`rm -rf "/Library/Application Support/SIMBL/Plugins/cDock.bundle"; killall -KILL Dock`

**Comment by eptik** [comment]
This command line solved the issue thanks !
