### ISSUE TITLE
cDock Helper cannot be opened because of a problem.

### ISSUE THREAD

**Issue by recuerom** [w0lfschild/cDock2#95]
Upgraded to 1.03 and I am getting this message every time I run Cdock on 10.13.4 with SIP off.

" cDock Helper cannot be opened because of a problem.

Check with the developer to make sure cDock Helper works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

Click Report to see more detailed information and send a report to Apple. "

I reinstalled Cdock (no uninstall) but no change.

**Comment by w0lfschild** [comment]
Will be fixed, next release.

**Comment by w0lfschild** [comment]
Should be fixed with 1.0.4
