### ISSUE TITLE
Dock pinning issue

### ISSUE THREAD

**Issue by Quantumpanda** [w0lfschild/cDock2#96]
When I select any dock pinning option, the Dock icon size shrinks down to 0 (though the number shown in cDock does not change) and does not actually change its pinning. The second selecting of a pinning option changes the pinning, as long as it's different from the first selection (the one that made the icons shrink).

After getting the pinning where I want it, selecting the icon size number (that doesn't reflect the fact that the icons have shrunk) and tabbing out of the field will restore the icon size—but the Dock grows from its center, regardless of where it's pinned, so if it's pinned "Top" or "Bottom", the icons on the end disappear off the side of the screen. Running the cursor over the Dock makes it jump to the correct pinning location.

**Comment by w0lfschild** [comment]
Hmm yup I'll have a fix for the Dock icon size shrinking next release.

Not sure about the issue where it doesn't change until the second selection, I'll look into that one.

**Comment by timvdhoorn** [comment]
Also what I experienced is that when the dock is off center, the magnification still registers only from the center.

**Comment by w0lfschild** [comment]
@timvdhoorn That is an issue I'm not sure how to fix. There is some sort of layer that still registers the original dock icons positions and I'm not sure what it is or how to adjust it with the icons. Thanks for the report though, it's something I definitely hope to fix in the future.

**Comment by w0lfschild** [comment]
Fixed the dock shrinking when changing position in 1.1.0
