### ISSUE TITLE
Conflict with Hot Corners on High Sierra 10.13.3

### ISSUE THREAD

**Issue by minimum91** [w0lfschild/cDock2#97]
This happens as soon as cDock is active in mySIMBL. If you look at the top right corner-ish, you can see that the mouse is bouncing there. Video demo attached. 
[Hot Corner Issue 720.zip](https://github.com/w0lfschild/cDock2/files/1851051/Hot.Corner.Issue.720.zip)

**Comment by w0lfschild** [comment]
I'll have a fix out for this in the next release. Thanks for the report.

**Comment by w0lfschild** [comment]
Fix is live in 1.1.0
