### ISSUE TITLE
cDock at Reset

### ISSUE THREAD

**Issue by Giorgior408** [w0lfschild/cDock2#99]
Mac OSX Yosemite    ( I have a license key )
Installed cDock 1.0.4
In "Preferences" - "Elements at login" entered cDock
OSX RESET
The SYSTEM Dock appears
Launch cDock
No action in dock
I press "Restart Dock"
The new Dock appears
Question:
Is it possible, on reset, to have the new Dock IMMEDIATELY?
Thank you

**Comment by w0lfschild** [comment]
Make sure the cDock Helper is showing up in your login items and you're using the latest version of cDock.

If it's not automatically showing up you can manually add it from this location

`/Applications/cDock.app/Contents/Resources/cDock Helper.app`
